// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/service/traffic_updater/proto/traffic.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficUpdateService_TriggerUpdate_FullMethodName = "/traffic.TrafficUpdateService/TriggerUpdate"
	TrafficUpdateService_GetStatus_FullMethodName     = "/traffic.TrafficUpdateService/GetStatus"
	TrafficUpdateService_UpdateTrip_FullMethodName    = "/traffic.TrafficUpdateService/UpdateTrip"
	TrafficUpdateService_StreetTraffic_FullMethodName = "/traffic.TrafficUpdateService/StreetTraffic"
	TrafficUpdateService_ListStreets_FullMethodName   = "/traffic.TrafficUpdateService/ListStreets"
)

// TrafficUpdateServiceClient is the client API for TrafficUpdateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficUpdateServiceClient interface {
	TriggerUpdate(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateTrip(ctx context.Context, in *UpdateTripRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	StreetTraffic(ctx context.Context, in *StreetTrafficRequest, opts ...grpc.CallOption) (*StreetTrafficResponse, error)
	ListStreets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StreetListResponse, error)
}

type trafficUpdateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficUpdateServiceClient(cc grpc.ClientConnInterface) TrafficUpdateServiceClient {
	return &trafficUpdateServiceClient{cc}
}

func (c *trafficUpdateServiceClient) TriggerUpdate(ctx context.Context, in *TriggerRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, TrafficUpdateService_TriggerUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficUpdateServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TrafficUpdateService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficUpdateServiceClient) UpdateTrip(ctx context.Context, in *UpdateTripRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, TrafficUpdateService_UpdateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficUpdateServiceClient) StreetTraffic(ctx context.Context, in *StreetTrafficRequest, opts ...grpc.CallOption) (*StreetTrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreetTrafficResponse)
	err := c.cc.Invoke(ctx, TrafficUpdateService_StreetTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficUpdateServiceClient) ListStreets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StreetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreetListResponse)
	err := c.cc.Invoke(ctx, TrafficUpdateService_ListStreets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficUpdateServiceServer is the server API for TrafficUpdateService service.
// All implementations must embed UnimplementedTrafficUpdateServiceServer
// for forward compatibility.
type TrafficUpdateServiceServer interface {
	TriggerUpdate(context.Context, *TriggerRequest) (*UpdateResponse, error)
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	UpdateTrip(context.Context, *UpdateTripRequest) (*UpdateResponse, error)
	StreetTraffic(context.Context, *StreetTrafficRequest) (*StreetTrafficResponse, error)
	ListStreets(context.Context, *Empty) (*StreetListResponse, error)
	mustEmbedUnimplementedTrafficUpdateServiceServer()
}

// UnimplementedTrafficUpdateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficUpdateServiceServer struct{}

func (UnimplementedTrafficUpdateServiceServer) TriggerUpdate(context.Context, *TriggerRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerUpdate not implemented")
}
func (UnimplementedTrafficUpdateServiceServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTrafficUpdateServiceServer) UpdateTrip(context.Context, *UpdateTripRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTrip not implemented")
}
func (UnimplementedTrafficUpdateServiceServer) StreetTraffic(context.Context, *StreetTrafficRequest) (*StreetTrafficResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StreetTraffic not implemented")
}
func (UnimplementedTrafficUpdateServiceServer) ListStreets(context.Context, *Empty) (*StreetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStreets not implemented")
}
func (UnimplementedTrafficUpdateServiceServer) mustEmbedUnimplementedTrafficUpdateServiceServer() {}
func (UnimplementedTrafficUpdateServiceServer) testEmbeddedByValue()                              {}

// UnsafeTrafficUpdateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficUpdateServiceServer will
// result in compilation errors.
type UnsafeTrafficUpdateServiceServer interface {
	mustEmbedUnimplementedTrafficUpdateServiceServer()
}

func RegisterTrafficUpdateServiceServer(s grpc.ServiceRegistrar, srv TrafficUpdateServiceServer) {
	// If the following call panics, it indicates UnimplementedTrafficUpdateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficUpdateService_ServiceDesc, srv)
}

func _TrafficUpdateService_TriggerUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficUpdateServiceServer).TriggerUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficUpdateService_TriggerUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficUpdateServiceServer).TriggerUpdate(ctx, req.(*TriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficUpdateService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficUpdateServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficUpdateService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficUpdateServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficUpdateService_UpdateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficUpdateServiceServer).UpdateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficUpdateService_UpdateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficUpdateServiceServer).UpdateTrip(ctx, req.(*UpdateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficUpdateService_StreetTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreetTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficUpdateServiceServer).StreetTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficUpdateService_StreetTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficUpdateServiceServer).StreetTraffic(ctx, req.(*StreetTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficUpdateService_ListStreets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficUpdateServiceServer).ListStreets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficUpdateService_ListStreets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficUpdateServiceServer).ListStreets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TrafficUpdateService_ServiceDesc is the grpc.ServiceDesc for TrafficUpdateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficUpdateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "traffic.TrafficUpdateService",
	HandlerType: (*TrafficUpdateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerUpdate",
			Handler:    _TrafficUpdateService_TriggerUpdate_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _TrafficUpdateService_GetStatus_Handler,
		},
		{
			MethodName: "UpdateTrip",
			Handler:    _TrafficUpdateService_UpdateTrip_Handler,
		},
		{
			MethodName: "StreetTraffic",
			Handler:    _TrafficUpdateService_StreetTraffic_Handler,
		},
		{
			MethodName: "ListStreets",
			Handler:    _TrafficUpdateService_ListStreets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/service/traffic_updater/proto/traffic.proto",
}
