// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/service/traffic_updater/proto/traffic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{0}
}

type TriggerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TripIds          []string               `protobuf:"bytes,1,rep,name=trip_ids,json=tripIds,proto3" json:"trip_ids,omitempty"` // empty = all trips
	NotifyRoutingApi bool                   `protobuf:"varint,2,opt,name=notify_routing_api,json=notifyRoutingApi,proto3" json:"notify_routing_api,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerRequest) GetTripIds() []string {
	if x != nil {
		return x.TripIds
	}
	return nil
}

func (x *TriggerRequest) GetNotifyRoutingApi() bool {
	if x != nil {
		return x.NotifyRoutingApi
	}
	return false
}

type UpdateTripRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TripId           string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	NotifyRoutingApi bool                   `protobuf:"varint,2,opt,name=notify_routing_api,json=notifyRoutingApi,proto3" json:"notify_routing_api,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateTripRequest) Reset() {
	*x = UpdateTripRequest{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripRequest) ProtoMessage() {}

func (x *UpdateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripRequest.ProtoReflect.Descriptor instead.
func (*UpdateTripRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *UpdateTripRequest) GetNotifyRoutingApi() bool {
	if x != nil {
		return x.NotifyRoutingApi
	}
	return false
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TripsUpdated  int32                  `protobuf:"varint,2,opt,name=trips_updated,json=tripsUpdated,proto3" json:"trips_updated,omitempty"`
	TripsFailed   int32                  `protobuf:"varint,3,opt,name=trips_failed,json=tripsFailed,proto3" json:"trips_failed,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateResponse) GetTripsUpdated() int32 {
	if x != nil {
		return x.TripsUpdated
	}
	return 0
}

func (x *UpdateResponse) GetTripsFailed() int32 {
	if x != nil {
		return x.TripsFailed
	}
	return 0
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LastUpdate    string                 `protobuf:"bytes,2,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	TripsInData   int32                  `protobuf:"varint,3,opt,name=trips_in_data,json=tripsInData,proto3" json:"trips_in_data,omitempty"`
	IsRunning     bool                   `protobuf:"varint,4,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

func (x *StatusResponse) GetTripsInData() int32 {
	if x != nil {
		return x.TripsInData
	}
	return 0
}

func (x *StatusResponse) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

type StreetTrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	MaxWaypoints  int32                  `protobuf:"varint,3,opt,name=max_waypoints,json=maxWaypoints,proto3" json:"max_waypoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreetTrafficRequest) Reset() {
	*x = StreetTrafficRequest{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreetTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreetTrafficRequest) ProtoMessage() {}

func (x *StreetTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreetTrafficRequest.ProtoReflect.Descriptor instead.
func (*StreetTrafficRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{5}
}

func (x *StreetTrafficRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreetTrafficRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *StreetTrafficRequest) GetMaxWaypoints() int32 {
	if x != nil {
		return x.MaxWaypoints
	}
	return 0
}

type StreetTrafficLeg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DistanceM       int32                  `protobuf:"varint,1,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
	DistanceText    string                 `protobuf:"bytes,2,opt,name=distance_text,json=distanceText,proto3" json:"distance_text,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	DurationText    string                 `protobuf:"bytes,4,opt,name=duration_text,json=durationText,proto3" json:"duration_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreetTrafficLeg) Reset() {
	*x = StreetTrafficLeg{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreetTrafficLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreetTrafficLeg) ProtoMessage() {}

func (x *StreetTrafficLeg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreetTrafficLeg.ProtoReflect.Descriptor instead.
func (*StreetTrafficLeg) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{6}
}

func (x *StreetTrafficLeg) GetDistanceM() int32 {
	if x != nil {
		return x.DistanceM
	}
	return 0
}

func (x *StreetTrafficLeg) GetDistanceText() string {
	if x != nil {
		return x.DistanceText
	}
	return ""
}

func (x *StreetTrafficLeg) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StreetTrafficLeg) GetDurationText() string {
	if x != nil {
		return x.DurationText
	}
	return ""
}

type StreetTrafficRoute struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Label           string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	DistanceM       int32                  `protobuf:"varint,2,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
	DistanceText    string                 `protobuf:"bytes,3,opt,name=distance_text,json=distanceText,proto3" json:"distance_text,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	DurationText    string                 `protobuf:"bytes,5,opt,name=duration_text,json=durationText,proto3" json:"duration_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreetTrafficRoute) Reset() {
	*x = StreetTrafficRoute{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreetTrafficRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreetTrafficRoute) ProtoMessage() {}

func (x *StreetTrafficRoute) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreetTrafficRoute.ProtoReflect.Descriptor instead.
func (*StreetTrafficRoute) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{7}
}

func (x *StreetTrafficRoute) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *StreetTrafficRoute) GetDistanceM() int32 {
	if x != nil {
		return x.DistanceM
	}
	return 0
}

func (x *StreetTrafficRoute) GetDistanceText() string {
	if x != nil {
		return x.DistanceText
	}
	return ""
}

func (x *StreetTrafficRoute) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StreetTrafficRoute) GetDurationText() string {
	if x != nil {
		return x.DurationText
	}
	return ""
}

type StreetTrafficResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Street           string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	StreetAr         string                 `protobuf:"bytes,2,opt,name=street_ar,json=streetAr,proto3" json:"street_ar,omitempty"`
	Segments         int32                  `protobuf:"varint,3,opt,name=segments,proto3" json:"segments,omitempty"`
	WaypointsUsed    int32                  `protobuf:"varint,4,opt,name=waypoints_used,json=waypointsUsed,proto3" json:"waypoints_used,omitempty"`
	TotalDistanceKm  float64                `protobuf:"fixed64,5,opt,name=total_distance_km,json=totalDistanceKm,proto3" json:"total_distance_km,omitempty"`
	TotalDurationMin float64                `protobuf:"fixed64,6,opt,name=total_duration_min,json=totalDurationMin,proto3" json:"total_duration_min,omitempty"`
	Legs             []*StreetTrafficLeg    `protobuf:"bytes,7,rep,name=legs,proto3" json:"legs,omitempty"`
	Routes           []*StreetTrafficRoute  `protobuf:"bytes,8,rep,name=routes,proto3" json:"routes,omitempty"`
	Error            string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreetTrafficResponse) Reset() {
	*x = StreetTrafficResponse{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreetTrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreetTrafficResponse) ProtoMessage() {}

func (x *StreetTrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreetTrafficResponse.ProtoReflect.Descriptor instead.
func (*StreetTrafficResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{8}
}

func (x *StreetTrafficResponse) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *StreetTrafficResponse) GetStreetAr() string {
	if x != nil {
		return x.StreetAr
	}
	return ""
}

func (x *StreetTrafficResponse) GetSegments() int32 {
	if x != nil {
		return x.Segments
	}
	return 0
}

func (x *StreetTrafficResponse) GetWaypointsUsed() int32 {
	if x != nil {
		return x.WaypointsUsed
	}
	return 0
}

func (x *StreetTrafficResponse) GetTotalDistanceKm() float64 {
	if x != nil {
		return x.TotalDistanceKm
	}
	return 0
}

func (x *StreetTrafficResponse) GetTotalDurationMin() float64 {
	if x != nil {
		return x.TotalDurationMin
	}
	return 0
}

func (x *StreetTrafficResponse) GetLegs() []*StreetTrafficLeg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *StreetTrafficResponse) GetRoutes() []*StreetTrafficRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *StreetTrafficResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NameAr        string                 `protobuf:"bytes,2,opt,name=name_ar,json=nameAr,proto3" json:"name_ar,omitempty"`
	Aliases       []string               `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Segments      int32                  `protobuf:"varint,4,opt,name=segments,proto3" json:"segments,omitempty"`
	TotalLengthKm float64                `protobuf:"fixed64,5,opt,name=total_length_km,json=totalLengthKm,proto3" json:"total_length_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreetInfo) Reset() {
	*x = StreetInfo{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreetInfo) ProtoMessage() {}

func (x *StreetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreetInfo.ProtoReflect.Descriptor instead.
func (*StreetInfo) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{9}
}

func (x *StreetInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreetInfo) GetNameAr() string {
	if x != nil {
		return x.NameAr
	}
	return ""
}

func (x *StreetInfo) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *StreetInfo) GetSegments() int32 {
	if x != nil {
		return x.Segments
	}
	return 0
}

func (x *StreetInfo) GetTotalLengthKm() float64 {
	if x != nil {
		return x.TotalLengthKm
	}
	return 0
}

type StreetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Streets       []*StreetInfo          `protobuf:"bytes,2,rep,name=streets,proto3" json:"streets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreetListResponse) Reset() {
	*x = StreetListResponse{}
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreetListResponse) ProtoMessage() {}

func (x *StreetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_traffic_updater_proto_traffic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreetListResponse.ProtoReflect.Descriptor instead.
func (*StreetListResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP(), []int{10}
}

func (x *StreetListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StreetListResponse) GetStreets() []*StreetInfo {
	if x != nil {
		return x.Streets
	}
	return nil
}

var File_internal_service_traffic_updater_proto_traffic_proto protoreflect.FileDescriptor

const file_internal_service_traffic_updater_proto_traffic_proto_rawDesc = "" +
	"\n" +
	"4internal/service/traffic_updater/proto/traffic.proto\x12\atraffic\"\a\n" +
	"\x05Empty\"Y\n" +
	"\x0eTriggerRequest\x12\x19\n" +
	"\btrip_ids\x18\x01 \x03(\tR\atripIds\x12,\n" +
	"\x12notify_routing_api\x18\x02 \x01(\bR\x10notifyRoutingApi\"Z\n" +
	"\x11UpdateTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12,\n" +
	"\x12notify_routing_api\x18\x02 \x01(\bR\x10notifyRoutingApi\"\x8a\x01\n" +
	"\x0eUpdateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rtrips_updated\x18\x02 \x01(\x05R\ftripsUpdated\x12!\n" +
	"\ftrips_failed\x18\x03 \x01(\x05R\vtripsFailed\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x8c\x01\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vlast_update\x18\x02 \x01(\tR\n" +
	"lastUpdate\x12\"\n" +
	"\rtrips_in_data\x18\x03 \x01(\x05R\vtripsInData\x12\x1d\n" +
	"\n" +
	"is_running\x18\x04 \x01(\bR\tisRunning\"k\n" +
	"\x14StreetTrafficRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12#\n" +
	"\rmax_waypoints\x18\x03 \x01(\x05R\fmaxWaypoints\"\xa6\x01\n" +
	"\x10StreetTrafficLeg\x12\x1d\n" +
	"\n" +
	"distance_m\x18\x01 \x01(\x05R\tdistanceM\x12#\n" +
	"\rdistance_text\x18\x02 \x01(\tR\fdistanceText\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\x12#\n" +
	"\rduration_text\x18\x04 \x01(\tR\fdurationText\"\xbe\x01\n" +
	"\x12StreetTrafficRoute\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"distance_m\x18\x02 \x01(\x05R\tdistanceM\x12#\n" +
	"\rdistance_text\x18\x03 \x01(\tR\fdistanceText\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\x12#\n" +
	"\rduration_text\x18\x05 \x01(\tR\fdurationText\"\xe3\x02\n" +
	"\x15StreetTrafficResponse\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x1b\n" +
	"\tstreet_ar\x18\x02 \x01(\tR\bstreetAr\x12\x1a\n" +
	"\bsegments\x18\x03 \x01(\x05R\bsegments\x12%\n" +
	"\x0ewaypoints_used\x18\x04 \x01(\x05R\rwaypointsUsed\x12*\n" +
	"\x11total_distance_km\x18\x05 \x01(\x01R\x0ftotalDistanceKm\x12,\n" +
	"\x12total_duration_min\x18\x06 \x01(\x01R\x10totalDurationMin\x12-\n" +
	"\x04legs\x18\a \x03(\v2\x19.traffic.StreetTrafficLegR\x04legs\x123\n" +
	"\x06routes\x18\b \x03(\v2\x1b.traffic.StreetTrafficRouteR\x06routes\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\x97\x01\n" +
	"\n" +
	"StreetInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aname_ar\x18\x02 \x01(\tR\x06nameAr\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\x12\x1a\n" +
	"\bsegments\x18\x04 \x01(\x05R\bsegments\x12&\n" +
	"\x0ftotal_length_km\x18\x05 \x01(\x01R\rtotalLengthKm\"Y\n" +
	"\x12StreetListResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12-\n" +
	"\astreets\x18\x02 \x03(\v2\x13.traffic.StreetInfoR\astreets2\xde\x02\n" +
	"\x14TrafficUpdateService\x12A\n" +
	"\rTriggerUpdate\x12\x17.traffic.TriggerRequest\x1a\x17.traffic.UpdateResponse\x124\n" +
	"\tGetStatus\x12\x0e.traffic.Empty\x1a\x17.traffic.StatusResponse\x12A\n" +
	"\n" +
	"UpdateTrip\x12\x1a.traffic.UpdateTripRequest\x1a\x17.traffic.UpdateResponse\x12N\n" +
	"\rStreetTraffic\x12\x1d.traffic.StreetTrafficRequest\x1a\x1e.traffic.StreetTrafficResponse\x12:\n" +
	"\vListStreets\x12\x0e.traffic.Empty\x1a\x1b.traffic.StreetListResponseBSZQgithub.com/Marwan051/final_project_backend/internal/service/traffic_updater/protob\x06proto3"

var (
	file_internal_service_traffic_updater_proto_traffic_proto_rawDescOnce sync.Once
	file_internal_service_traffic_updater_proto_traffic_proto_rawDescData []byte
)

func file_internal_service_traffic_updater_proto_traffic_proto_rawDescGZIP() []byte {
	file_internal_service_traffic_updater_proto_traffic_proto_rawDescOnce.Do(func() {
		file_internal_service_traffic_updater_proto_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_service_traffic_updater_proto_traffic_proto_rawDesc), len(file_internal_service_traffic_updater_proto_traffic_proto_rawDesc)))
	})
	return file_internal_service_traffic_updater_proto_traffic_proto_rawDescData
}

var file_internal_service_traffic_updater_proto_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_service_traffic_updater_proto_traffic_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: traffic.Empty
	(*TriggerRequest)(nil),        // 1: traffic.TriggerRequest
	(*UpdateTripRequest)(nil),     // 2: traffic.UpdateTripRequest
	(*UpdateResponse)(nil),        // 3: traffic.UpdateResponse
	(*StatusResponse)(nil),        // 4: traffic.StatusResponse
	(*StreetTrafficRequest)(nil),  // 5: traffic.StreetTrafficRequest
	(*StreetTrafficLeg)(nil),      // 6: traffic.StreetTrafficLeg
	(*StreetTrafficRoute)(nil),    // 7: traffic.StreetTrafficRoute
	(*StreetTrafficResponse)(nil), // 8: traffic.StreetTrafficResponse
	(*StreetInfo)(nil),            // 9: traffic.StreetInfo
	(*StreetListResponse)(nil),    // 10: traffic.StreetListResponse
}
var file_internal_service_traffic_updater_proto_traffic_proto_depIdxs = []int32{
	6,  // 0: traffic.StreetTrafficResponse.legs:type_name -> traffic.StreetTrafficLeg
	7,  // 1: traffic.StreetTrafficResponse.routes:type_name -> traffic.StreetTrafficRoute
	9,  // 2: traffic.StreetListResponse.streets:type_name -> traffic.StreetInfo
	1,  // 3: traffic.TrafficUpdateService.TriggerUpdate:input_type -> traffic.TriggerRequest
	0,  // 4: traffic.TrafficUpdateService.GetStatus:input_type -> traffic.Empty
	2,  // 5: traffic.TrafficUpdateService.UpdateTrip:input_type -> traffic.UpdateTripRequest
	5,  // 6: traffic.TrafficUpdateService.StreetTraffic:input_type -> traffic.StreetTrafficRequest
	0,  // 7: traffic.TrafficUpdateService.ListStreets:input_type -> traffic.Empty
	3,  // 8: traffic.TrafficUpdateService.TriggerUpdate:output_type -> traffic.UpdateResponse
	4,  // 9: traffic.TrafficUpdateService.GetStatus:output_type -> traffic.StatusResponse
	3,  // 10: traffic.TrafficUpdateService.UpdateTrip:output_type -> traffic.UpdateResponse
	8,  // 11: traffic.TrafficUpdateService.StreetTraffic:output_type -> traffic.StreetTrafficResponse
	10, // 12: traffic.TrafficUpdateService.ListStreets:output_type -> traffic.StreetListResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_service_traffic_updater_proto_traffic_proto_init() }
func file_internal_service_traffic_updater_proto_traffic_proto_init() {
	if File_internal_service_traffic_updater_proto_traffic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_traffic_updater_proto_traffic_proto_rawDesc), len(file_internal_service_traffic_updater_proto_traffic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_traffic_updater_proto_traffic_proto_goTypes,
		DependencyIndexes: file_internal_service_traffic_updater_proto_traffic_proto_depIdxs,
		MessageInfos:      file_internal_service_traffic_updater_proto_traffic_proto_msgTypes,
	}.Build()
	File_internal_service_traffic_updater_proto_traffic_proto = out.File
	file_internal_service_traffic_updater_proto_traffic_proto_goTypes = nil
	file_internal_service_traffic_updater_proto_traffic_proto_depIdxs = nil
}
