// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/service/agent/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserQuery     string                 `protobuf:"bytes,1,opt,name=user_query,json=userQuery,proto3" json:"user_query,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Unique identifier for memory tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_internal_service_agent_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_agent_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_agent_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequest) GetUserQuery() string {
	if x != nil {
		return x.UserQuery
	}
	return ""
}

func (x *AgentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_internal_service_agent_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_agent_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_agent_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AgentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_service_agent_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_agent_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_agent_proto_agent_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_service_agent_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_agent_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_agent_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_service_agent_proto_agent_proto protoreflect.FileDescriptor

const file_internal_service_agent_proto_agent_proto_rawDesc = "" +
	"\n" +
	"(internal/service/agent/proto/agent.proto\x12\x05agent\"L\n" +
	"\fAgentRequest\x12\x1d\n" +
	"\n" +
	"user_query\x18\x01 \x01(\tR\tuserQuery\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"F\n" +
	"\rAgentResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x85\x01\n" +
	"\fAgentService\x129\n" +
	"\fProcessQuery\x12\x13.agent.AgentRequest\x1a\x14.agent.AgentResponse\x12:\n" +
	"\vHealthCheck\x12\x14.agent.HealthRequest\x1a\x15.agent.HealthResponseBIZGgithub.com/Marwan051/final_project_backend/internal/service/agent/protob\x06proto3"

var (
	file_internal_service_agent_proto_agent_proto_rawDescOnce sync.Once
	file_internal_service_agent_proto_agent_proto_rawDescData []byte
)

func file_internal_service_agent_proto_agent_proto_rawDescGZIP() []byte {
	file_internal_service_agent_proto_agent_proto_rawDescOnce.Do(func() {
		file_internal_service_agent_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_service_agent_proto_agent_proto_rawDesc), len(file_internal_service_agent_proto_agent_proto_rawDesc)))
	})
	return file_internal_service_agent_proto_agent_proto_rawDescData
}

var file_internal_service_agent_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_service_agent_proto_agent_proto_goTypes = []any{
	(*AgentRequest)(nil),   // 0: agent.AgentRequest
	(*AgentResponse)(nil),  // 1: agent.AgentResponse
	(*HealthRequest)(nil),  // 2: agent.HealthRequest
	(*HealthResponse)(nil), // 3: agent.HealthResponse
}
var file_internal_service_agent_proto_agent_proto_depIdxs = []int32{
	0, // 0: agent.AgentService.ProcessQuery:input_type -> agent.AgentRequest
	2, // 1: agent.AgentService.HealthCheck:input_type -> agent.HealthRequest
	1, // 2: agent.AgentService.ProcessQuery:output_type -> agent.AgentResponse
	3, // 3: agent.AgentService.HealthCheck:output_type -> agent.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_service_agent_proto_agent_proto_init() }
func file_internal_service_agent_proto_agent_proto_init() {
	if File_internal_service_agent_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_agent_proto_agent_proto_rawDesc), len(file_internal_service_agent_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_agent_proto_agent_proto_goTypes,
		DependencyIndexes: file_internal_service_agent_proto_agent_proto_depIdxs,
		MessageInfos:      file_internal_service_agent_proto_agent_proto_msgTypes,
	}.Build()
	File_internal_service_agent_proto_agent_proto = out.File
	file_internal_service_agent_proto_agent_proto_goTypes = nil
	file_internal_service_agent_proto_agent_proto_depIdxs = nil
}
