syntax = "proto3";


option go_package = "github.com/Marwan051/final_project_backend/internal/service/agent/proto";

package agent;

service AgentService {
  rpc ProcessQuery(AgentRequest) returns (AgentResponse);
  rpc HealthCheck(HealthRequest) returns (HealthResponse);
}

message AgentRequest {
  string user_query = 1;
  string session_id = 2;  // Unique identifier for memory tracking
}

message AgentResponse {
  string answer = 1;
  string session_id = 2;
}

message HealthRequest {}

message HealthResponse {
  string status = 1;
}