// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Route struct {
	RouteID           int64
	FeedID            pgtype.Text
	Code              pgtype.Text
	Name              string
	ContinuousPickup  bool
	ContinuousDropOff bool
	Mode              pgtype.Text
	Cost              int32
	OneWay            bool
	Operator          pgtype.Text
	Attrs             []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type RouteGeometry struct {
	RouteGeomID int64
	RouteID     int64
	Geom4326    interface{}
	Geom22992   interface{}
	Attrs       []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RouteStop struct {
	RouteStopID   int64
	RouteID       int64
	StopID        int64
	StopSequence  int32
	ArrivalTime   pgtype.Time
	DepartureTime pgtype.Time
	Attrs         []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type StageRoute struct {
	RouteIDText   pgtype.Text
	Code          pgtype.Text
	Name          pgtype.Text
	KindText      pgtype.Text
	Mode          pgtype.Text
	CostText      pgtype.Text
	OneWayText    pgtype.Text
	Operator      pgtype.Text
	AttrsText     pgtype.Text
	CreatedAtText pgtype.Text
	UpdatedAtText pgtype.Text
}

type StageRouteGeometry struct {
	RouteGeomIDText pgtype.Text
	RouteIDText     pgtype.Text
	GeomWkt         pgtype.Text
	AttrsText       pgtype.Text
	CreatedAtText   pgtype.Text
	UpdatedAtText   pgtype.Text
}

type StageRouteStop struct {
	RouteStopIDText   pgtype.Text
	RouteIDText       pgtype.Text
	StopIDText        pgtype.Text
	StopSequenceText  pgtype.Text
	ArrivalTimeText   pgtype.Text
	DepartureTimeText pgtype.Text
	AttrsText         pgtype.Text
	CreatedAtText     pgtype.Text
	UpdatedAtText     pgtype.Text
}

type StageStop struct {
	Code          pgtype.Text
	Name          pgtype.Text
	GeomWkt       pgtype.Text
	AttrsText     pgtype.Text
	CreatedAtText pgtype.Text
	UpdatedAtText pgtype.Text
}

type Stop struct {
	StopID    int64
	Code      pgtype.Text
	Name      pgtype.Text
	Geom4326  interface{}
	Geom22992 interface{}
	Attrs     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
