// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"
)

const getAllRoutes = `-- name: GetAllRoutes :many
SELECT route_id, feed_id, code, name, continuous_pickup, continuous_drop_off, mode, cost, one_way, operator, attrs, created_at, updated_at
FROM ROUTES
`

func (q *Queries) GetAllRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, getAllRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.RouteID,
			&i.FeedID,
			&i.Code,
			&i.Name,
			&i.ContinuousPickup,
			&i.ContinuousDropOff,
			&i.Mode,
			&i.Cost,
			&i.OneWay,
			&i.Operator,
			&i.Attrs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
