// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: internal/service/route_service/proto/route.proto

package routing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check request (empty)
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_route_service_proto_route_proto_rawDescGZIP(), []int{0}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_route_service_proto_route_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for finding a route
type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLon      float64                `protobuf:"fixed64,1,opt,name=start_lon,json=startLon,proto3" json:"start_lon,omitempty"`
	StartLat      float64                `protobuf:"fixed64,2,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	EndLon        float64                `protobuf:"fixed64,3,opt,name=end_lon,json=endLon,proto3" json:"end_lon,omitempty"`
	EndLat        float64                `protobuf:"fixed64,4,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	MaxTransfers  int32                  `protobuf:"varint,5,opt,name=max_transfers,json=maxTransfers,proto3" json:"max_transfers,omitempty"`
	WalkingCutoff float64                `protobuf:"fixed64,6,opt,name=walking_cutoff,json=walkingCutoff,proto3" json:"walking_cutoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_route_service_proto_route_proto_rawDescGZIP(), []int{2}
}

func (x *RouteRequest) GetStartLon() float64 {
	if x != nil {
		return x.StartLon
	}
	return 0
}

func (x *RouteRequest) GetStartLat() float64 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *RouteRequest) GetEndLon() float64 {
	if x != nil {
		return x.EndLon
	}
	return 0
}

func (x *RouteRequest) GetEndLat() float64 {
	if x != nil {
		return x.EndLat
	}
	return 0
}

func (x *RouteRequest) GetMaxTransfers() int32 {
	if x != nil {
		return x.MaxTransfers
	}
	return 0
}

func (x *RouteRequest) GetWalkingCutoff() float64 {
	if x != nil {
		return x.WalkingCutoff
	}
	return 0
}

// Cost information for a journey
type JourneyCosts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Money         float64                `protobuf:"fixed64,1,opt,name=money,proto3" json:"money,omitempty"`
	TransportTime float64                `protobuf:"fixed64,2,opt,name=transport_time,json=transportTime,proto3" json:"transport_time,omitempty"`
	Walk          float64                `protobuf:"fixed64,3,opt,name=walk,proto3" json:"walk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JourneyCosts) Reset() {
	*x = JourneyCosts{}
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyCosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyCosts) ProtoMessage() {}

func (x *JourneyCosts) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyCosts.ProtoReflect.Descriptor instead.
func (*JourneyCosts) Descriptor() ([]byte, []int) {
	return file_internal_service_route_service_proto_route_proto_rawDescGZIP(), []int{3}
}

func (x *JourneyCosts) GetMoney() float64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *JourneyCosts) GetTransportTime() float64 {
	if x != nil {
		return x.TransportTime
	}
	return 0
}

func (x *JourneyCosts) GetWalk() float64 {
	if x != nil {
		return x.Walk
	}
	return 0
}

// A single journey with path and costs
type Journey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Costs         *JourneyCosts          `protobuf:"bytes,2,opt,name=costs,proto3" json:"costs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Journey) Reset() {
	*x = Journey{}
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Journey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Journey) ProtoMessage() {}

func (x *Journey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Journey.ProtoReflect.Descriptor instead.
func (*Journey) Descriptor() ([]byte, []int) {
	return file_internal_service_route_service_proto_route_proto_rawDescGZIP(), []int{4}
}

func (x *Journey) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Journey) GetCosts() *JourneyCosts {
	if x != nil {
		return x.Costs
	}
	return nil
}

// Response containing all found journeys
type RouteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NumJourneys     int32                  `protobuf:"varint,1,opt,name=num_journeys,json=numJourneys,proto3" json:"num_journeys,omitempty"`
	Journeys        []*Journey             `protobuf:"bytes,2,rep,name=journeys,proto3" json:"journeys,omitempty"`
	StartTripsFound int32                  `protobuf:"varint,3,opt,name=start_trips_found,json=startTripsFound,proto3" json:"start_trips_found,omitempty"`
	EndTripsFound   int32                  `protobuf:"varint,4,opt,name=end_trips_found,json=endTripsFound,proto3" json:"end_trips_found,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_route_service_proto_route_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_route_service_proto_route_proto_rawDescGZIP(), []int{5}
}

func (x *RouteResponse) GetNumJourneys() int32 {
	if x != nil {
		return x.NumJourneys
	}
	return 0
}

func (x *RouteResponse) GetJourneys() []*Journey {
	if x != nil {
		return x.Journeys
	}
	return nil
}

func (x *RouteResponse) GetStartTripsFound() int32 {
	if x != nil {
		return x.StartTripsFound
	}
	return 0
}

func (x *RouteResponse) GetEndTripsFound() int32 {
	if x != nil {
		return x.EndTripsFound
	}
	return 0
}

var File_internal_service_route_service_proto_route_proto protoreflect.FileDescriptor

const file_internal_service_route_service_proto_route_proto_rawDesc = "" +
	"\n" +
	"0internal/service/route_service/proto/route.proto\x12\arouting\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc6\x01\n" +
	"\fRouteRequest\x12\x1b\n" +
	"\tstart_lon\x18\x01 \x01(\x01R\bstartLon\x12\x1b\n" +
	"\tstart_lat\x18\x02 \x01(\x01R\bstartLat\x12\x17\n" +
	"\aend_lon\x18\x03 \x01(\x01R\x06endLon\x12\x17\n" +
	"\aend_lat\x18\x04 \x01(\x01R\x06endLat\x12#\n" +
	"\rmax_transfers\x18\x05 \x01(\x05R\fmaxTransfers\x12%\n" +
	"\x0ewalking_cutoff\x18\x06 \x01(\x01R\rwalkingCutoff\"_\n" +
	"\fJourneyCosts\x12\x14\n" +
	"\x05money\x18\x01 \x01(\x01R\x05money\x12%\n" +
	"\x0etransport_time\x18\x02 \x01(\x01R\rtransportTime\x12\x12\n" +
	"\x04walk\x18\x03 \x01(\x01R\x04walk\"J\n" +
	"\aJourney\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path\x12+\n" +
	"\x05costs\x18\x02 \x01(\v2\x15.routing.JourneyCostsR\x05costs\"\xb4\x01\n" +
	"\rRouteResponse\x12!\n" +
	"\fnum_journeys\x18\x01 \x01(\x05R\vnumJourneys\x12,\n" +
	"\bjourneys\x18\x02 \x03(\v2\x10.routing.JourneyR\bjourneys\x12*\n" +
	"\x11start_trips_found\x18\x03 \x01(\x05R\x0fstartTripsFound\x12&\n" +
	"\x0fend_trips_found\x18\x04 \x01(\x05R\rendTripsFound2\x90\x01\n" +
	"\x0eRoutingService\x12@\n" +
	"\vHealthCheck\x12\x16.routing.HealthRequest\x1a\x17.routing.HealthResponse\"\x00\x12<\n" +
	"\tFindRoute\x12\x15.routing.RouteRequest\x1a\x16.routing.RouteResponse\"\x00BYZWgithub.com/Marwan051/final_project_backend/internal/service/route_service/proto;routingb\x06proto3"

var (
	file_internal_service_route_service_proto_route_proto_rawDescOnce sync.Once
	file_internal_service_route_service_proto_route_proto_rawDescData []byte
)

func file_internal_service_route_service_proto_route_proto_rawDescGZIP() []byte {
	file_internal_service_route_service_proto_route_proto_rawDescOnce.Do(func() {
		file_internal_service_route_service_proto_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_service_route_service_proto_route_proto_rawDesc), len(file_internal_service_route_service_proto_route_proto_rawDesc)))
	})
	return file_internal_service_route_service_proto_route_proto_rawDescData
}

var file_internal_service_route_service_proto_route_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_service_route_service_proto_route_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: routing.HealthRequest
	(*HealthResponse)(nil), // 1: routing.HealthResponse
	(*RouteRequest)(nil),   // 2: routing.RouteRequest
	(*JourneyCosts)(nil),   // 3: routing.JourneyCosts
	(*Journey)(nil),        // 4: routing.Journey
	(*RouteResponse)(nil),  // 5: routing.RouteResponse
}
var file_internal_service_route_service_proto_route_proto_depIdxs = []int32{
	3, // 0: routing.Journey.costs:type_name -> routing.JourneyCosts
	4, // 1: routing.RouteResponse.journeys:type_name -> routing.Journey
	0, // 2: routing.RoutingService.HealthCheck:input_type -> routing.HealthRequest
	2, // 3: routing.RoutingService.FindRoute:input_type -> routing.RouteRequest
	1, // 4: routing.RoutingService.HealthCheck:output_type -> routing.HealthResponse
	5, // 5: routing.RoutingService.FindRoute:output_type -> routing.RouteResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_service_route_service_proto_route_proto_init() }
func file_internal_service_route_service_proto_route_proto_init() {
	if File_internal_service_route_service_proto_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_route_service_proto_route_proto_rawDesc), len(file_internal_service_route_service_proto_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_route_service_proto_route_proto_goTypes,
		DependencyIndexes: file_internal_service_route_service_proto_route_proto_depIdxs,
		MessageInfos:      file_internal_service_route_service_proto_route_proto_msgTypes,
	}.Build()
	File_internal_service_route_service_proto_route_proto = out.File
	file_internal_service_route_service_proto_route_proto_goTypes = nil
	file_internal_service_route_service_proto_route_proto_depIdxs = nil
}
