// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: routing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check request (empty)
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{0}
}

// Health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for finding a route
type RouteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartLon        float64                `protobuf:"fixed64,1,opt,name=start_lon,json=startLon,proto3" json:"start_lon,omitempty"`
	StartLat        float64                `protobuf:"fixed64,2,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	EndLon          float64                `protobuf:"fixed64,3,opt,name=end_lon,json=endLon,proto3" json:"end_lon,omitempty"`
	EndLat          float64                `protobuf:"fixed64,4,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	MaxTransfers    int32                  `protobuf:"varint,5,opt,name=max_transfers,json=maxTransfers,proto3" json:"max_transfers,omitempty"`
	WalkingCutoff   float64                `protobuf:"fixed64,6,opt,name=walking_cutoff,json=walkingCutoff,proto3" json:"walking_cutoff,omitempty"`
	RestrictedModes []string               `protobuf:"bytes,7,rep,name=restricted_modes,json=restrictedModes,proto3" json:"restricted_modes,omitempty"`
	Weights         *RoutingWeights        `protobuf:"bytes,8,opt,name=weights,proto3" json:"weights,omitempty"`
	TopK            int32                  `protobuf:"varint,9,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{2}
}

func (x *RouteRequest) GetStartLon() float64 {
	if x != nil {
		return x.StartLon
	}
	return 0
}

func (x *RouteRequest) GetStartLat() float64 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *RouteRequest) GetEndLon() float64 {
	if x != nil {
		return x.EndLon
	}
	return 0
}

func (x *RouteRequest) GetEndLat() float64 {
	if x != nil {
		return x.EndLat
	}
	return 0
}

func (x *RouteRequest) GetMaxTransfers() int32 {
	if x != nil {
		return x.MaxTransfers
	}
	return 0
}

func (x *RouteRequest) GetWalkingCutoff() float64 {
	if x != nil {
		return x.WalkingCutoff
	}
	return 0
}

func (x *RouteRequest) GetRestrictedModes() []string {
	if x != nil {
		return x.RestrictedModes
	}
	return nil
}

func (x *RouteRequest) GetWeights() *RoutingWeights {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *RouteRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

// Routing weights for journey ranking
type RoutingWeights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          float64                `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	Cost          float64                `protobuf:"fixed64,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Walk          float64                `protobuf:"fixed64,3,opt,name=walk,proto3" json:"walk,omitempty"`
	Transfer      float64                `protobuf:"fixed64,4,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingWeights) Reset() {
	*x = RoutingWeights{}
	mi := &file_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingWeights) ProtoMessage() {}

func (x *RoutingWeights) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingWeights.ProtoReflect.Descriptor instead.
func (*RoutingWeights) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{3}
}

func (x *RoutingWeights) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RoutingWeights) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *RoutingWeights) GetWalk() float64 {
	if x != nil {
		return x.Walk
	}
	return 0
}

func (x *RoutingWeights) GetTransfer() float64 {
	if x != nil {
		return x.Transfer
	}
	return 0
}

// Response containing all found journeys
type RouteResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NumJourneys      int32                  `protobuf:"varint,1,opt,name=num_journeys,json=numJourneys,proto3" json:"num_journeys,omitempty"`
	Journeys         []*Journey             `protobuf:"bytes,2,rep,name=journeys,proto3" json:"journeys,omitempty"`
	StartTripsFound  int32                  `protobuf:"varint,3,opt,name=start_trips_found,json=startTripsFound,proto3" json:"start_trips_found,omitempty"`
	EndTripsFound    int32                  `protobuf:"varint,4,opt,name=end_trips_found,json=endTripsFound,proto3" json:"end_trips_found,omitempty"`
	TotalRoutesFound int32                  `protobuf:"varint,5,opt,name=total_routes_found,json=totalRoutesFound,proto3" json:"total_routes_found,omitempty"`
	Error            string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{4}
}

func (x *RouteResponse) GetNumJourneys() int32 {
	if x != nil {
		return x.NumJourneys
	}
	return 0
}

func (x *RouteResponse) GetJourneys() []*Journey {
	if x != nil {
		return x.Journeys
	}
	return nil
}

func (x *RouteResponse) GetStartTripsFound() int32 {
	if x != nil {
		return x.StartTripsFound
	}
	return 0
}

func (x *RouteResponse) GetEndTripsFound() int32 {
	if x != nil {
		return x.EndTripsFound
	}
	return 0
}

func (x *RouteResponse) GetTotalRoutesFound() int32 {
	if x != nil {
		return x.TotalRoutesFound
	}
	return 0
}

func (x *RouteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// A single journey option
type Journey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TextSummary   string                 `protobuf:"bytes,2,opt,name=text_summary,json=textSummary,proto3" json:"text_summary,omitempty"`
	Summary       *JourneySummary        `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Legs          []*Leg                 `protobuf:"bytes,4,rep,name=legs,proto3" json:"legs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Journey) Reset() {
	*x = Journey{}
	mi := &file_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Journey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Journey) ProtoMessage() {}

func (x *Journey) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Journey.ProtoReflect.Descriptor instead.
func (*Journey) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{5}
}

func (x *Journey) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Journey) GetTextSummary() string {
	if x != nil {
		return x.TextSummary
	}
	return ""
}

func (x *Journey) GetSummary() *JourneySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Journey) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

// Summary of journey metrics
type JourneySummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalTimeMinutes      int32                  `protobuf:"varint,1,opt,name=total_time_minutes,json=totalTimeMinutes,proto3" json:"total_time_minutes,omitempty"`
	TotalDistanceMeters   int32                  `protobuf:"varint,2,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	WalkingDistanceMeters int32                  `protobuf:"varint,3,opt,name=walking_distance_meters,json=walkingDistanceMeters,proto3" json:"walking_distance_meters,omitempty"`
	Transfers             int32                  `protobuf:"varint,4,opt,name=transfers,proto3" json:"transfers,omitempty"`
	Cost                  float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Modes                 []string               `protobuf:"bytes,6,rep,name=modes,proto3" json:"modes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JourneySummary) Reset() {
	*x = JourneySummary{}
	mi := &file_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneySummary) ProtoMessage() {}

func (x *JourneySummary) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneySummary.ProtoReflect.Descriptor instead.
func (*JourneySummary) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{6}
}

func (x *JourneySummary) GetTotalTimeMinutes() int32 {
	if x != nil {
		return x.TotalTimeMinutes
	}
	return 0
}

func (x *JourneySummary) GetTotalDistanceMeters() int32 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *JourneySummary) GetWalkingDistanceMeters() int32 {
	if x != nil {
		return x.WalkingDistanceMeters
	}
	return 0
}

func (x *JourneySummary) GetTransfers() int32 {
	if x != nil {
		return x.Transfers
	}
	return 0
}

func (x *JourneySummary) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *JourneySummary) GetModes() []string {
	if x != nil {
		return x.Modes
	}
	return nil
}

// A leg of the journey (walk, trip, or transfer)
type Leg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to LegType:
	//
	//	*Leg_Walk
	//	*Leg_Trip
	//	*Leg_Transfer
	LegType       isLeg_LegType `protobuf_oneof:"leg_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leg) Reset() {
	*x = Leg{}
	mi := &file_routing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leg) ProtoMessage() {}

func (x *Leg) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leg.ProtoReflect.Descriptor instead.
func (*Leg) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{7}
}

func (x *Leg) GetLegType() isLeg_LegType {
	if x != nil {
		return x.LegType
	}
	return nil
}

func (x *Leg) GetWalk() *WalkLeg {
	if x != nil {
		if x, ok := x.LegType.(*Leg_Walk); ok {
			return x.Walk
		}
	}
	return nil
}

func (x *Leg) GetTrip() *TripLeg {
	if x != nil {
		if x, ok := x.LegType.(*Leg_Trip); ok {
			return x.Trip
		}
	}
	return nil
}

func (x *Leg) GetTransfer() *TransferLeg {
	if x != nil {
		if x, ok := x.LegType.(*Leg_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

type isLeg_LegType interface {
	isLeg_LegType()
}

type Leg_Walk struct {
	Walk *WalkLeg `protobuf:"bytes,1,opt,name=walk,proto3,oneof"`
}

type Leg_Trip struct {
	Trip *TripLeg `protobuf:"bytes,2,opt,name=trip,proto3,oneof"`
}

type Leg_Transfer struct {
	Transfer *TransferLeg `protobuf:"bytes,3,opt,name=transfer,proto3,oneof"`
}

func (*Leg_Walk) isLeg_LegType() {}

func (*Leg_Trip) isLeg_LegType() {}

func (*Leg_Transfer) isLeg_LegType() {}

// Walking leg
type WalkLeg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DistanceMeters  int32                  `protobuf:"varint,1,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Path            []*Coordinate          `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WalkLeg) Reset() {
	*x = WalkLeg{}
	mi := &file_routing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkLeg) ProtoMessage() {}

func (x *WalkLeg) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkLeg.ProtoReflect.Descriptor instead.
func (*WalkLeg) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{8}
}

func (x *WalkLeg) GetDistanceMeters() int32 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *WalkLeg) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *WalkLeg) GetPath() []*Coordinate {
	if x != nil {
		return x.Path
	}
	return nil
}

// Transit trip leg
type TripLeg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TripId          string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Mode            string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	RouteShortName  string                 `protobuf:"bytes,3,opt,name=route_short_name,json=routeShortName,proto3" json:"route_short_name,omitempty"`
	Headsign        string                 `protobuf:"bytes,4,opt,name=headsign,proto3" json:"headsign,omitempty"`
	Fare            float64                `protobuf:"fixed64,5,opt,name=fare,proto3" json:"fare,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	From            *Stop                  `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	To              *Stop                  `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	Path            []*Coordinate          `protobuf:"bytes,9,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TripLeg) Reset() {
	*x = TripLeg{}
	mi := &file_routing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripLeg) ProtoMessage() {}

func (x *TripLeg) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripLeg.ProtoReflect.Descriptor instead.
func (*TripLeg) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{9}
}

func (x *TripLeg) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripLeg) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TripLeg) GetRouteShortName() string {
	if x != nil {
		return x.RouteShortName
	}
	return ""
}

func (x *TripLeg) GetHeadsign() string {
	if x != nil {
		return x.Headsign
	}
	return ""
}

func (x *TripLeg) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *TripLeg) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *TripLeg) GetFrom() *Stop {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TripLeg) GetTo() *Stop {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TripLeg) GetPath() []*Coordinate {
	if x != nil {
		return x.Path
	}
	return nil
}

// Transfer between trips
type TransferLeg struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FromTripId            string                 `protobuf:"bytes,1,opt,name=from_trip_id,json=fromTripId,proto3" json:"from_trip_id,omitempty"`
	ToTripId              string                 `protobuf:"bytes,2,opt,name=to_trip_id,json=toTripId,proto3" json:"to_trip_id,omitempty"`
	FromTripName          string                 `protobuf:"bytes,3,opt,name=from_trip_name,json=fromTripName,proto3" json:"from_trip_name,omitempty"`
	ToTripName            string                 `protobuf:"bytes,4,opt,name=to_trip_name,json=toTripName,proto3" json:"to_trip_name,omitempty"`
	WalkingDistanceMeters int32                  `protobuf:"varint,5,opt,name=walking_distance_meters,json=walkingDistanceMeters,proto3" json:"walking_distance_meters,omitempty"`
	DurationMinutes       int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Path                  []*Coordinate          `protobuf:"bytes,7,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TransferLeg) Reset() {
	*x = TransferLeg{}
	mi := &file_routing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeg) ProtoMessage() {}

func (x *TransferLeg) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeg.ProtoReflect.Descriptor instead.
func (*TransferLeg) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{10}
}

func (x *TransferLeg) GetFromTripId() string {
	if x != nil {
		return x.FromTripId
	}
	return ""
}

func (x *TransferLeg) GetToTripId() string {
	if x != nil {
		return x.ToTripId
	}
	return ""
}

func (x *TransferLeg) GetFromTripName() string {
	if x != nil {
		return x.FromTripName
	}
	return ""
}

func (x *TransferLeg) GetToTripName() string {
	if x != nil {
		return x.ToTripName
	}
	return ""
}

func (x *TransferLeg) GetWalkingDistanceMeters() int32 {
	if x != nil {
		return x.WalkingDistanceMeters
	}
	return 0
}

func (x *TransferLeg) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *TransferLeg) GetPath() []*Coordinate {
	if x != nil {
		return x.Path
	}
	return nil
}

// Stop information
type Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopId        int32                  `protobuf:"varint,1,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Coord         *Coordinate            `protobuf:"bytes,3,opt,name=coord,proto3" json:"coord,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stop) Reset() {
	*x = Stop{}
	mi := &file_routing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{11}
}

func (x *Stop) GetStopId() int32 {
	if x != nil {
		return x.StopId
	}
	return 0
}

func (x *Stop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stop) GetCoord() *Coordinate {
	if x != nil {
		return x.Coord
	}
	return nil
}

// Coordinate (lon, lat)
type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lon           float64                `protobuf:"fixed64,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_routing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_routing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_routing_proto_rawDescGZIP(), []int{12}
}

func (x *Coordinate) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Coordinate) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

var File_routing_proto protoreflect.FileDescriptor

const file_routing_proto_rawDesc = "" +
	"\n" +
	"\rrouting.proto\x12\x05proto\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb7\x02\n" +
	"\fRouteRequest\x12\x1b\n" +
	"\tstart_lon\x18\x01 \x01(\x01R\bstartLon\x12\x1b\n" +
	"\tstart_lat\x18\x02 \x01(\x01R\bstartLat\x12\x17\n" +
	"\aend_lon\x18\x03 \x01(\x01R\x06endLon\x12\x17\n" +
	"\aend_lat\x18\x04 \x01(\x01R\x06endLat\x12#\n" +
	"\rmax_transfers\x18\x05 \x01(\x05R\fmaxTransfers\x12%\n" +
	"\x0ewalking_cutoff\x18\x06 \x01(\x01R\rwalkingCutoff\x12)\n" +
	"\x10restricted_modes\x18\a \x03(\tR\x0frestrictedModes\x12/\n" +
	"\aweights\x18\b \x01(\v2\x15.proto.RoutingWeightsR\aweights\x12\x13\n" +
	"\x05top_k\x18\t \x01(\x05R\x04topK\"h\n" +
	"\x0eRoutingWeights\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x01R\x04time\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x01R\x04cost\x12\x12\n" +
	"\x04walk\x18\x03 \x01(\x01R\x04walk\x12\x1a\n" +
	"\btransfer\x18\x04 \x01(\x01R\btransfer\"\xf6\x01\n" +
	"\rRouteResponse\x12!\n" +
	"\fnum_journeys\x18\x01 \x01(\x05R\vnumJourneys\x12*\n" +
	"\bjourneys\x18\x02 \x03(\v2\x0e.proto.JourneyR\bjourneys\x12*\n" +
	"\x11start_trips_found\x18\x03 \x01(\x05R\x0fstartTripsFound\x12&\n" +
	"\x0fend_trips_found\x18\x04 \x01(\x05R\rendTripsFound\x12,\n" +
	"\x12total_routes_found\x18\x05 \x01(\x05R\x10totalRoutesFound\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x8d\x01\n" +
	"\aJourney\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\ftext_summary\x18\x02 \x01(\tR\vtextSummary\x12/\n" +
	"\asummary\x18\x03 \x01(\v2\x15.proto.JourneySummaryR\asummary\x12\x1e\n" +
	"\x04legs\x18\x04 \x03(\v2\n" +
	".proto.LegR\x04legs\"\xf2\x01\n" +
	"\x0eJourneySummary\x12,\n" +
	"\x12total_time_minutes\x18\x01 \x01(\x05R\x10totalTimeMinutes\x122\n" +
	"\x15total_distance_meters\x18\x02 \x01(\x05R\x13totalDistanceMeters\x126\n" +
	"\x17walking_distance_meters\x18\x03 \x01(\x05R\x15walkingDistanceMeters\x12\x1c\n" +
	"\ttransfers\x18\x04 \x01(\x05R\ttransfers\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12\x14\n" +
	"\x05modes\x18\x06 \x03(\tR\x05modes\"\x8f\x01\n" +
	"\x03Leg\x12$\n" +
	"\x04walk\x18\x01 \x01(\v2\x0e.proto.WalkLegH\x00R\x04walk\x12$\n" +
	"\x04trip\x18\x02 \x01(\v2\x0e.proto.TripLegH\x00R\x04trip\x120\n" +
	"\btransfer\x18\x03 \x01(\v2\x12.proto.TransferLegH\x00R\btransferB\n" +
	"\n" +
	"\bleg_type\"\x84\x01\n" +
	"\aWalkLeg\x12'\n" +
	"\x0fdistance_meters\x18\x01 \x01(\x05R\x0edistanceMeters\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\x12%\n" +
	"\x04path\x18\x03 \x03(\v2\x11.proto.CoordinateR\x04path\"\xa0\x02\n" +
	"\aTripLeg\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12(\n" +
	"\x10route_short_name\x18\x03 \x01(\tR\x0erouteShortName\x12\x1a\n" +
	"\bheadsign\x18\x04 \x01(\tR\bheadsign\x12\x12\n" +
	"\x04fare\x18\x05 \x01(\x01R\x04fare\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes\x12\x1f\n" +
	"\x04from\x18\a \x01(\v2\v.proto.StopR\x04from\x12\x1b\n" +
	"\x02to\x18\b \x01(\v2\v.proto.StopR\x02to\x12%\n" +
	"\x04path\x18\t \x03(\v2\x11.proto.CoordinateR\x04path\"\x9f\x02\n" +
	"\vTransferLeg\x12 \n" +
	"\ffrom_trip_id\x18\x01 \x01(\tR\n" +
	"fromTripId\x12\x1c\n" +
	"\n" +
	"to_trip_id\x18\x02 \x01(\tR\btoTripId\x12$\n" +
	"\x0efrom_trip_name\x18\x03 \x01(\tR\ffromTripName\x12 \n" +
	"\fto_trip_name\x18\x04 \x01(\tR\n" +
	"toTripName\x126\n" +
	"\x17walking_distance_meters\x18\x05 \x01(\x05R\x15walkingDistanceMeters\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes\x12%\n" +
	"\x04path\x18\a \x03(\v2\x11.proto.CoordinateR\x04path\"\\\n" +
	"\x04Stop\x12\x17\n" +
	"\astop_id\x18\x01 \x01(\x05R\x06stopId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x05coord\x18\x03 \x01(\v2\x11.proto.CoordinateR\x05coord\"0\n" +
	"\n" +
	"Coordinate\x12\x10\n" +
	"\x03lon\x18\x01 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat2\x88\x01\n" +
	"\x0eRoutingService\x12<\n" +
	"\vHealthCheck\x12\x14.proto.HealthRequest\x1a\x15.proto.HealthResponse\"\x00\x128\n" +
	"\tFindRoute\x12\x13.proto.RouteRequest\x1a\x14.proto.RouteResponse\"\x00BQZOgithub.com/Marwan051/final_project_backend/internal/service/route_service/protob\x06proto3"

var (
	file_routing_proto_rawDescOnce sync.Once
	file_routing_proto_rawDescData []byte
)

func file_routing_proto_rawDescGZIP() []byte {
	file_routing_proto_rawDescOnce.Do(func() {
		file_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)))
	})
	return file_routing_proto_rawDescData
}

var file_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_routing_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: proto.HealthRequest
	(*HealthResponse)(nil), // 1: proto.HealthResponse
	(*RouteRequest)(nil),   // 2: proto.RouteRequest
	(*RoutingWeights)(nil), // 3: proto.RoutingWeights
	(*RouteResponse)(nil),  // 4: proto.RouteResponse
	(*Journey)(nil),        // 5: proto.Journey
	(*JourneySummary)(nil), // 6: proto.JourneySummary
	(*Leg)(nil),            // 7: proto.Leg
	(*WalkLeg)(nil),        // 8: proto.WalkLeg
	(*TripLeg)(nil),        // 9: proto.TripLeg
	(*TransferLeg)(nil),    // 10: proto.TransferLeg
	(*Stop)(nil),           // 11: proto.Stop
	(*Coordinate)(nil),     // 12: proto.Coordinate
}
var file_routing_proto_depIdxs = []int32{
	3,  // 0: proto.RouteRequest.weights:type_name -> proto.RoutingWeights
	5,  // 1: proto.RouteResponse.journeys:type_name -> proto.Journey
	6,  // 2: proto.Journey.summary:type_name -> proto.JourneySummary
	7,  // 3: proto.Journey.legs:type_name -> proto.Leg
	8,  // 4: proto.Leg.walk:type_name -> proto.WalkLeg
	9,  // 5: proto.Leg.trip:type_name -> proto.TripLeg
	10, // 6: proto.Leg.transfer:type_name -> proto.TransferLeg
	12, // 7: proto.WalkLeg.path:type_name -> proto.Coordinate
	11, // 8: proto.TripLeg.from:type_name -> proto.Stop
	11, // 9: proto.TripLeg.to:type_name -> proto.Stop
	12, // 10: proto.TripLeg.path:type_name -> proto.Coordinate
	12, // 11: proto.TransferLeg.path:type_name -> proto.Coordinate
	12, // 12: proto.Stop.coord:type_name -> proto.Coordinate
	0,  // 13: proto.RoutingService.HealthCheck:input_type -> proto.HealthRequest
	2,  // 14: proto.RoutingService.FindRoute:input_type -> proto.RouteRequest
	1,  // 15: proto.RoutingService.HealthCheck:output_type -> proto.HealthResponse
	4,  // 16: proto.RoutingService.FindRoute:output_type -> proto.RouteResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_routing_proto_init() }
func file_routing_proto_init() {
	if File_routing_proto != nil {
		return
	}
	file_routing_proto_msgTypes[7].OneofWrappers = []any{
		(*Leg_Walk)(nil),
		(*Leg_Trip)(nil),
		(*Leg_Transfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_proto_rawDesc), len(file_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routing_proto_goTypes,
		DependencyIndexes: file_routing_proto_depIdxs,
		MessageInfos:      file_routing_proto_msgTypes,
	}.Build()
	File_routing_proto = out.File
	file_routing_proto_goTypes = nil
	file_routing_proto_depIdxs = nil
}
