// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/service/routing/proto/routing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{0}
}

type FilterBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []string               `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	IncludeMatch  string                 `protobuf:"bytes,3,opt,name=include_match,json=includeMatch,proto3" json:"include_match,omitempty"` // "any" or "all"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterBlock) Reset() {
	*x = FilterBlock{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterBlock) ProtoMessage() {}

func (x *FilterBlock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterBlock.ProtoReflect.Descriptor instead.
func (*FilterBlock) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{1}
}

func (x *FilterBlock) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *FilterBlock) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *FilterBlock) GetIncludeMatch() string {
	if x != nil {
		return x.IncludeMatch
	}
	return ""
}

type Filters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modes         *FilterBlock           `protobuf:"bytes,1,opt,name=modes,proto3" json:"modes,omitempty"`
	MainStreets   *FilterBlock           `protobuf:"bytes,2,opt,name=main_streets,json=mainStreets,proto3" json:"main_streets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filters) Reset() {
	*x = Filters{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filters) ProtoMessage() {}

func (x *Filters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filters.ProtoReflect.Descriptor instead.
func (*Filters) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{2}
}

func (x *Filters) GetModes() *FilterBlock {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *Filters) GetMainStreets() *FilterBlock {
	if x != nil {
		return x.MainStreets
	}
	return nil
}

type JourneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLat      float64                `protobuf:"fixed64,1,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLon      float64                `protobuf:"fixed64,2,opt,name=start_lon,json=startLon,proto3" json:"start_lon,omitempty"`
	EndLat        float64                `protobuf:"fixed64,3,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	EndLon        float64                `protobuf:"fixed64,4,opt,name=end_lon,json=endLon,proto3" json:"end_lon,omitempty"`
	MaxTransfers  int32                  `protobuf:"varint,5,opt,name=max_transfers,json=maxTransfers,proto3" json:"max_transfers,omitempty"`
	WalkingCutoff int32                  `protobuf:"varint,6,opt,name=walking_cutoff,json=walkingCutoff,proto3" json:"walking_cutoff,omitempty"`
	Priority      string                 `protobuf:"bytes,7,opt,name=priority,proto3" json:"priority,omitempty"`
	TopK          int32                  `protobuf:"varint,8,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filters       *Filters               `protobuf:"bytes,9,opt,name=filters,proto3" json:"filters,omitempty"`
	Weights       map[string]float64     `protobuf:"bytes,10,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JourneyRequest) Reset() {
	*x = JourneyRequest{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyRequest) ProtoMessage() {}

func (x *JourneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyRequest.ProtoReflect.Descriptor instead.
func (*JourneyRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{3}
}

func (x *JourneyRequest) GetStartLat() float64 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *JourneyRequest) GetStartLon() float64 {
	if x != nil {
		return x.StartLon
	}
	return 0
}

func (x *JourneyRequest) GetEndLat() float64 {
	if x != nil {
		return x.EndLat
	}
	return 0
}

func (x *JourneyRequest) GetEndLon() float64 {
	if x != nil {
		return x.EndLon
	}
	return 0
}

func (x *JourneyRequest) GetMaxTransfers() int32 {
	if x != nil {
		return x.MaxTransfers
	}
	return 0
}

func (x *JourneyRequest) GetWalkingCutoff() int32 {
	if x != nil {
		return x.WalkingCutoff
	}
	return 0
}

func (x *JourneyRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *JourneyRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *JourneyRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *JourneyRequest) GetWeights() map[string]float64 {
	if x != nil {
		return x.Weights
	}
	return nil
}

type StopInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopId        string                 `protobuf:"bytes,1,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameAr        string                 `protobuf:"bytes,3,opt,name=name_ar,json=nameAr,proto3" json:"name_ar,omitempty"`
	Coord         []float64              `protobuf:"fixed64,4,rep,packed,name=coord,proto3" json:"coord,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInfo) Reset() {
	*x = StopInfo{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInfo) ProtoMessage() {}

func (x *StopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInfo.ProtoReflect.Descriptor instead.
func (*StopInfo) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{4}
}

func (x *StopInfo) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *StopInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StopInfo) GetNameAr() string {
	if x != nil {
		return x.NameAr
	}
	return ""
}

func (x *StopInfo) GetCoord() []float64 {
	if x != nil {
		return x.Coord
	}
	return nil
}

type Leg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Walk leg fields
	DistanceMeters  int32  `protobuf:"varint,2,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationMinutes int32  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Polyline        string `protobuf:"bytes,4,opt,name=polyline,proto3" json:"polyline,omitempty"`
	// Trip leg fields
	TripId           string    `protobuf:"bytes,5,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	TripIds          []string  `protobuf:"bytes,6,rep,name=trip_ids,json=tripIds,proto3" json:"trip_ids,omitempty"`
	ModeEn           string    `protobuf:"bytes,7,opt,name=mode_en,json=modeEn,proto3" json:"mode_en,omitempty"`
	ModeAr           string    `protobuf:"bytes,8,opt,name=mode_ar,json=modeAr,proto3" json:"mode_ar,omitempty"`
	RouteShortName   string    `protobuf:"bytes,9,opt,name=route_short_name,json=routeShortName,proto3" json:"route_short_name,omitempty"`
	RouteShortNameAr string    `protobuf:"bytes,10,opt,name=route_short_name_ar,json=routeShortNameAr,proto3" json:"route_short_name_ar,omitempty"`
	Headsign         string    `protobuf:"bytes,11,opt,name=headsign,proto3" json:"headsign,omitempty"`
	HeadsignAr       string    `protobuf:"bytes,12,opt,name=headsign_ar,json=headsignAr,proto3" json:"headsign_ar,omitempty"`
	Fare             float64   `protobuf:"fixed64,13,opt,name=fare,proto3" json:"fare,omitempty"`
	FromStop         *StopInfo `protobuf:"bytes,14,opt,name=from_stop,json=fromStop,proto3" json:"from_stop,omitempty"`
	ToStop           *StopInfo `protobuf:"bytes,15,opt,name=to_stop,json=toStop,proto3" json:"to_stop,omitempty"`
	// Transfer leg fields
	FromTripId            string `protobuf:"bytes,16,opt,name=from_trip_id,json=fromTripId,proto3" json:"from_trip_id,omitempty"`
	ToTripId              string `protobuf:"bytes,17,opt,name=to_trip_id,json=toTripId,proto3" json:"to_trip_id,omitempty"`
	FromTripName          string `protobuf:"bytes,18,opt,name=from_trip_name,json=fromTripName,proto3" json:"from_trip_name,omitempty"`
	FromTripNameAr        string `protobuf:"bytes,19,opt,name=from_trip_name_ar,json=fromTripNameAr,proto3" json:"from_trip_name_ar,omitempty"`
	ToTripName            string `protobuf:"bytes,20,opt,name=to_trip_name,json=toTripName,proto3" json:"to_trip_name,omitempty"`
	ToTripNameAr          string `protobuf:"bytes,21,opt,name=to_trip_name_ar,json=toTripNameAr,proto3" json:"to_trip_name_ar,omitempty"`
	EndStopId             string `protobuf:"bytes,22,opt,name=end_stop_id,json=endStopId,proto3" json:"end_stop_id,omitempty"`
	WalkingDistanceMeters int32  `protobuf:"varint,23,opt,name=walking_distance_meters,json=walkingDistanceMeters,proto3" json:"walking_distance_meters,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Leg) Reset() {
	*x = Leg{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leg) ProtoMessage() {}

func (x *Leg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leg.ProtoReflect.Descriptor instead.
func (*Leg) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{5}
}

func (x *Leg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Leg) GetDistanceMeters() int32 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *Leg) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *Leg) GetPolyline() string {
	if x != nil {
		return x.Polyline
	}
	return ""
}

func (x *Leg) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *Leg) GetTripIds() []string {
	if x != nil {
		return x.TripIds
	}
	return nil
}

func (x *Leg) GetModeEn() string {
	if x != nil {
		return x.ModeEn
	}
	return ""
}

func (x *Leg) GetModeAr() string {
	if x != nil {
		return x.ModeAr
	}
	return ""
}

func (x *Leg) GetRouteShortName() string {
	if x != nil {
		return x.RouteShortName
	}
	return ""
}

func (x *Leg) GetRouteShortNameAr() string {
	if x != nil {
		return x.RouteShortNameAr
	}
	return ""
}

func (x *Leg) GetHeadsign() string {
	if x != nil {
		return x.Headsign
	}
	return ""
}

func (x *Leg) GetHeadsignAr() string {
	if x != nil {
		return x.HeadsignAr
	}
	return ""
}

func (x *Leg) GetFare() float64 {
	if x != nil {
		return x.Fare
	}
	return 0
}

func (x *Leg) GetFromStop() *StopInfo {
	if x != nil {
		return x.FromStop
	}
	return nil
}

func (x *Leg) GetToStop() *StopInfo {
	if x != nil {
		return x.ToStop
	}
	return nil
}

func (x *Leg) GetFromTripId() string {
	if x != nil {
		return x.FromTripId
	}
	return ""
}

func (x *Leg) GetToTripId() string {
	if x != nil {
		return x.ToTripId
	}
	return ""
}

func (x *Leg) GetFromTripName() string {
	if x != nil {
		return x.FromTripName
	}
	return ""
}

func (x *Leg) GetFromTripNameAr() string {
	if x != nil {
		return x.FromTripNameAr
	}
	return ""
}

func (x *Leg) GetToTripName() string {
	if x != nil {
		return x.ToTripName
	}
	return ""
}

func (x *Leg) GetToTripNameAr() string {
	if x != nil {
		return x.ToTripNameAr
	}
	return ""
}

func (x *Leg) GetEndStopId() string {
	if x != nil {
		return x.EndStopId
	}
	return ""
}

func (x *Leg) GetWalkingDistanceMeters() int32 {
	if x != nil {
		return x.WalkingDistanceMeters
	}
	return 0
}

type JourneySummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalTimeMinutes      int32                  `protobuf:"varint,1,opt,name=total_time_minutes,json=totalTimeMinutes,proto3" json:"total_time_minutes,omitempty"`
	WalkingDistanceMeters int32                  `protobuf:"varint,2,opt,name=walking_distance_meters,json=walkingDistanceMeters,proto3" json:"walking_distance_meters,omitempty"`
	TransitDistanceMeters int32                  `protobuf:"varint,3,opt,name=transit_distance_meters,json=transitDistanceMeters,proto3" json:"transit_distance_meters,omitempty"`
	TotalDistanceMeters   int32                  `protobuf:"varint,4,opt,name=total_distance_meters,json=totalDistanceMeters,proto3" json:"total_distance_meters,omitempty"`
	Transfers             int32                  `protobuf:"varint,5,opt,name=transfers,proto3" json:"transfers,omitempty"`
	Cost                  float64                `protobuf:"fixed64,6,opt,name=cost,proto3" json:"cost,omitempty"`
	ModesEn               []string               `protobuf:"bytes,7,rep,name=modes_en,json=modesEn,proto3" json:"modes_en,omitempty"`
	ModesAr               []string               `protobuf:"bytes,8,rep,name=modes_ar,json=modesAr,proto3" json:"modes_ar,omitempty"`
	MainStreetsEn         []string               `protobuf:"bytes,9,rep,name=main_streets_en,json=mainStreetsEn,proto3" json:"main_streets_en,omitempty"`
	MainStreetsAr         []string               `protobuf:"bytes,10,rep,name=main_streets_ar,json=mainStreetsAr,proto3" json:"main_streets_ar,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JourneySummary) Reset() {
	*x = JourneySummary{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneySummary) ProtoMessage() {}

func (x *JourneySummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneySummary.ProtoReflect.Descriptor instead.
func (*JourneySummary) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{6}
}

func (x *JourneySummary) GetTotalTimeMinutes() int32 {
	if x != nil {
		return x.TotalTimeMinutes
	}
	return 0
}

func (x *JourneySummary) GetWalkingDistanceMeters() int32 {
	if x != nil {
		return x.WalkingDistanceMeters
	}
	return 0
}

func (x *JourneySummary) GetTransitDistanceMeters() int32 {
	if x != nil {
		return x.TransitDistanceMeters
	}
	return 0
}

func (x *JourneySummary) GetTotalDistanceMeters() int32 {
	if x != nil {
		return x.TotalDistanceMeters
	}
	return 0
}

func (x *JourneySummary) GetTransfers() int32 {
	if x != nil {
		return x.Transfers
	}
	return 0
}

func (x *JourneySummary) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *JourneySummary) GetModesEn() []string {
	if x != nil {
		return x.ModesEn
	}
	return nil
}

func (x *JourneySummary) GetModesAr() []string {
	if x != nil {
		return x.ModesAr
	}
	return nil
}

func (x *JourneySummary) GetMainStreetsEn() []string {
	if x != nil {
		return x.MainStreetsEn
	}
	return nil
}

func (x *JourneySummary) GetMainStreetsAr() []string {
	if x != nil {
		return x.MainStreetsAr
	}
	return nil
}

type Journey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TextSummary    string                 `protobuf:"bytes,2,opt,name=text_summary,json=textSummary,proto3" json:"text_summary,omitempty"`
	TextSummaryEn  string                 `protobuf:"bytes,3,opt,name=text_summary_en,json=textSummaryEn,proto3" json:"text_summary_en,omitempty"`
	Summary        *JourneySummary        `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Legs           []*Leg                 `protobuf:"bytes,5,rep,name=legs,proto3" json:"legs,omitempty"`
	Labels         []string               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	LabelsAr       []string               `protobuf:"bytes,7,rep,name=labels_ar,json=labelsAr,proto3" json:"labels_ar,omitempty"`
	RecommendedFor string                 `protobuf:"bytes,8,opt,name=recommended_for,json=recommendedFor,proto3" json:"recommended_for,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Journey) Reset() {
	*x = Journey{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Journey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Journey) ProtoMessage() {}

func (x *Journey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Journey.ProtoReflect.Descriptor instead.
func (*Journey) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{7}
}

func (x *Journey) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Journey) GetTextSummary() string {
	if x != nil {
		return x.TextSummary
	}
	return ""
}

func (x *Journey) GetTextSummaryEn() string {
	if x != nil {
		return x.TextSummaryEn
	}
	return ""
}

func (x *Journey) GetSummary() *JourneySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Journey) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Journey) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Journey) GetLabelsAr() []string {
	if x != nil {
		return x.LabelsAr
	}
	return nil
}

func (x *Journey) GetRecommendedFor() string {
	if x != nil {
		return x.RecommendedFor
	}
	return ""
}

type JourneyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GeometryEncoding string                 `protobuf:"bytes,1,opt,name=geometry_encoding,json=geometryEncoding,proto3" json:"geometry_encoding,omitempty"`
	SelectedPriority string                 `protobuf:"bytes,2,opt,name=selected_priority,json=selectedPriority,proto3" json:"selected_priority,omitempty"`
	WeightsUsed      map[string]float64     `protobuf:"bytes,3,rep,name=weights_used,json=weightsUsed,proto3" json:"weights_used,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	NumJourneys      int32                  `protobuf:"varint,4,opt,name=num_journeys,json=numJourneys,proto3" json:"num_journeys,omitempty"`
	Journeys         []*Journey             `protobuf:"bytes,5,rep,name=journeys,proto3" json:"journeys,omitempty"`
	StartTripsFound  int32                  `protobuf:"varint,6,opt,name=start_trips_found,json=startTripsFound,proto3" json:"start_trips_found,omitempty"`
	EndTripsFound    int32                  `protobuf:"varint,7,opt,name=end_trips_found,json=endTripsFound,proto3" json:"end_trips_found,omitempty"`
	TotalRoutesFound int32                  `protobuf:"varint,8,opt,name=total_routes_found,json=totalRoutesFound,proto3" json:"total_routes_found,omitempty"`
	TotalAfterDedup  int32                  `protobuf:"varint,9,opt,name=total_after_dedup,json=totalAfterDedup,proto3" json:"total_after_dedup,omitempty"`
	Error            string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JourneyResponse) Reset() {
	*x = JourneyResponse{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JourneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JourneyResponse) ProtoMessage() {}

func (x *JourneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JourneyResponse.ProtoReflect.Descriptor instead.
func (*JourneyResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{8}
}

func (x *JourneyResponse) GetGeometryEncoding() string {
	if x != nil {
		return x.GeometryEncoding
	}
	return ""
}

func (x *JourneyResponse) GetSelectedPriority() string {
	if x != nil {
		return x.SelectedPriority
	}
	return ""
}

func (x *JourneyResponse) GetWeightsUsed() map[string]float64 {
	if x != nil {
		return x.WeightsUsed
	}
	return nil
}

func (x *JourneyResponse) GetNumJourneys() int32 {
	if x != nil {
		return x.NumJourneys
	}
	return 0
}

func (x *JourneyResponse) GetJourneys() []*Journey {
	if x != nil {
		return x.Journeys
	}
	return nil
}

func (x *JourneyResponse) GetStartTripsFound() int32 {
	if x != nil {
		return x.StartTripsFound
	}
	return 0
}

func (x *JourneyResponse) GetEndTripsFound() int32 {
	if x != nil {
		return x.EndTripsFound
	}
	return 0
}

func (x *JourneyResponse) GetTotalRoutesFound() int32 {
	if x != nil {
		return x.TotalRoutesFound
	}
	return 0
}

func (x *JourneyResponse) GetTotalAfterDedup() int32 {
	if x != nil {
		return x.TotalAfterDedup
	}
	return 0
}

func (x *JourneyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	GraphNodes     int32                  `protobuf:"varint,2,opt,name=graph_nodes,json=graphNodes,proto3" json:"graph_nodes,omitempty"`
	GraphEdges     int32                  `protobuf:"varint,3,opt,name=graph_edges,json=graphEdges,proto3" json:"graph_edges,omitempty"`
	TripGraphEdges int32                  `protobuf:"varint,4,opt,name=trip_graph_edges,json=tripGraphEdges,proto3" json:"trip_graph_edges,omitempty"`
	TripsLoaded    int32                  `protobuf:"varint,5,opt,name=trips_loaded,json=tripsLoaded,proto3" json:"trips_loaded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_routing_proto_routing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_routing_proto_routing_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetGraphNodes() int32 {
	if x != nil {
		return x.GraphNodes
	}
	return 0
}

func (x *HealthResponse) GetGraphEdges() int32 {
	if x != nil {
		return x.GraphEdges
	}
	return 0
}

func (x *HealthResponse) GetTripGraphEdges() int32 {
	if x != nil {
		return x.TripGraphEdges
	}
	return 0
}

func (x *HealthResponse) GetTripsLoaded() int32 {
	if x != nil {
		return x.TripsLoaded
	}
	return 0
}

var File_internal_service_routing_proto_routing_proto protoreflect.FileDescriptor

const file_internal_service_routing_proto_routing_proto_rawDesc = "" +
	"\n" +
	",internal/service/routing/proto/routing.proto\x12\arouting\"\a\n" +
	"\x05Empty\"f\n" +
	"\vFilterBlock\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\x12#\n" +
	"\rinclude_match\x18\x03 \x01(\tR\fincludeMatch\"n\n" +
	"\aFilters\x12*\n" +
	"\x05modes\x18\x01 \x01(\v2\x14.routing.FilterBlockR\x05modes\x127\n" +
	"\fmain_streets\x18\x02 \x01(\v2\x14.routing.FilterBlockR\vmainStreets\"\xa1\x03\n" +
	"\x0eJourneyRequest\x12\x1b\n" +
	"\tstart_lat\x18\x01 \x01(\x01R\bstartLat\x12\x1b\n" +
	"\tstart_lon\x18\x02 \x01(\x01R\bstartLon\x12\x17\n" +
	"\aend_lat\x18\x03 \x01(\x01R\x06endLat\x12\x17\n" +
	"\aend_lon\x18\x04 \x01(\x01R\x06endLon\x12#\n" +
	"\rmax_transfers\x18\x05 \x01(\x05R\fmaxTransfers\x12%\n" +
	"\x0ewalking_cutoff\x18\x06 \x01(\x05R\rwalkingCutoff\x12\x1a\n" +
	"\bpriority\x18\a \x01(\tR\bpriority\x12\x13\n" +
	"\x05top_k\x18\b \x01(\x05R\x04topK\x12*\n" +
	"\afilters\x18\t \x01(\v2\x10.routing.FiltersR\afilters\x12>\n" +
	"\aweights\x18\n" +
	" \x03(\v2$.routing.JourneyRequest.WeightsEntryR\aweights\x1a:\n" +
	"\fWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"f\n" +
	"\bStopInfo\x12\x17\n" +
	"\astop_id\x18\x01 \x01(\tR\x06stopId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aname_ar\x18\x03 \x01(\tR\x06nameAr\x12\x14\n" +
	"\x05coord\x18\x04 \x03(\x01R\x05coord\"\xa7\x06\n" +
	"\x03Leg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12'\n" +
	"\x0fdistance_meters\x18\x02 \x01(\x05R\x0edistanceMeters\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\x12\x1a\n" +
	"\bpolyline\x18\x04 \x01(\tR\bpolyline\x12\x17\n" +
	"\atrip_id\x18\x05 \x01(\tR\x06tripId\x12\x19\n" +
	"\btrip_ids\x18\x06 \x03(\tR\atripIds\x12\x17\n" +
	"\amode_en\x18\a \x01(\tR\x06modeEn\x12\x17\n" +
	"\amode_ar\x18\b \x01(\tR\x06modeAr\x12(\n" +
	"\x10route_short_name\x18\t \x01(\tR\x0erouteShortName\x12-\n" +
	"\x13route_short_name_ar\x18\n" +
	" \x01(\tR\x10routeShortNameAr\x12\x1a\n" +
	"\bheadsign\x18\v \x01(\tR\bheadsign\x12\x1f\n" +
	"\vheadsign_ar\x18\f \x01(\tR\n" +
	"headsignAr\x12\x12\n" +
	"\x04fare\x18\r \x01(\x01R\x04fare\x12.\n" +
	"\tfrom_stop\x18\x0e \x01(\v2\x11.routing.StopInfoR\bfromStop\x12*\n" +
	"\ato_stop\x18\x0f \x01(\v2\x11.routing.StopInfoR\x06toStop\x12 \n" +
	"\ffrom_trip_id\x18\x10 \x01(\tR\n" +
	"fromTripId\x12\x1c\n" +
	"\n" +
	"to_trip_id\x18\x11 \x01(\tR\btoTripId\x12$\n" +
	"\x0efrom_trip_name\x18\x12 \x01(\tR\ffromTripName\x12)\n" +
	"\x11from_trip_name_ar\x18\x13 \x01(\tR\x0efromTripNameAr\x12 \n" +
	"\fto_trip_name\x18\x14 \x01(\tR\n" +
	"toTripName\x12%\n" +
	"\x0fto_trip_name_ar\x18\x15 \x01(\tR\ftoTripNameAr\x12\x1e\n" +
	"\vend_stop_id\x18\x16 \x01(\tR\tendStopId\x126\n" +
	"\x17walking_distance_meters\x18\x17 \x01(\x05R\x15walkingDistanceMeters\"\x9a\x03\n" +
	"\x0eJourneySummary\x12,\n" +
	"\x12total_time_minutes\x18\x01 \x01(\x05R\x10totalTimeMinutes\x126\n" +
	"\x17walking_distance_meters\x18\x02 \x01(\x05R\x15walkingDistanceMeters\x126\n" +
	"\x17transit_distance_meters\x18\x03 \x01(\x05R\x15transitDistanceMeters\x122\n" +
	"\x15total_distance_meters\x18\x04 \x01(\x05R\x13totalDistanceMeters\x12\x1c\n" +
	"\ttransfers\x18\x05 \x01(\x05R\ttransfers\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x01R\x04cost\x12\x19\n" +
	"\bmodes_en\x18\a \x03(\tR\amodesEn\x12\x19\n" +
	"\bmodes_ar\x18\b \x03(\tR\amodesAr\x12&\n" +
	"\x0fmain_streets_en\x18\t \x03(\tR\rmainStreetsEn\x12&\n" +
	"\x0fmain_streets_ar\x18\n" +
	" \x03(\tR\rmainStreetsAr\"\x97\x02\n" +
	"\aJourney\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\ftext_summary\x18\x02 \x01(\tR\vtextSummary\x12&\n" +
	"\x0ftext_summary_en\x18\x03 \x01(\tR\rtextSummaryEn\x121\n" +
	"\asummary\x18\x04 \x01(\v2\x17.routing.JourneySummaryR\asummary\x12 \n" +
	"\x04legs\x18\x05 \x03(\v2\f.routing.LegR\x04legs\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x12\x1b\n" +
	"\tlabels_ar\x18\a \x03(\tR\blabelsAr\x12'\n" +
	"\x0frecommended_for\x18\b \x01(\tR\x0erecommendedFor\"\x8e\x04\n" +
	"\x0fJourneyResponse\x12+\n" +
	"\x11geometry_encoding\x18\x01 \x01(\tR\x10geometryEncoding\x12+\n" +
	"\x11selected_priority\x18\x02 \x01(\tR\x10selectedPriority\x12L\n" +
	"\fweights_used\x18\x03 \x03(\v2).routing.JourneyResponse.WeightsUsedEntryR\vweightsUsed\x12!\n" +
	"\fnum_journeys\x18\x04 \x01(\x05R\vnumJourneys\x12,\n" +
	"\bjourneys\x18\x05 \x03(\v2\x10.routing.JourneyR\bjourneys\x12*\n" +
	"\x11start_trips_found\x18\x06 \x01(\x05R\x0fstartTripsFound\x12&\n" +
	"\x0fend_trips_found\x18\a \x01(\x05R\rendTripsFound\x12,\n" +
	"\x12total_routes_found\x18\b \x01(\x05R\x10totalRoutesFound\x12*\n" +
	"\x11total_after_dedup\x18\t \x01(\x05R\x0ftotalAfterDedup\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x1a>\n" +
	"\x10WeightsUsedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xb7\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vgraph_nodes\x18\x02 \x01(\x05R\n" +
	"graphNodes\x12\x1f\n" +
	"\vgraph_edges\x18\x03 \x01(\x05R\n" +
	"graphEdges\x12(\n" +
	"\x10trip_graph_edges\x18\x04 \x01(\x05R\x0etripGraphEdges\x12!\n" +
	"\ftrips_loaded\x18\x05 \x01(\x05R\vtripsLoaded2\x8b\x01\n" +
	"\x0eRoutingService\x12A\n" +
	"\fFindJourneys\x12\x17.routing.JourneyRequest\x1a\x18.routing.JourneyResponse\x126\n" +
	"\vHealthCheck\x12\x0e.routing.Empty\x1a\x17.routing.HealthResponseBKZIgithub.com/Marwan051/final_project_backend/internal/service/routing/protob\x06proto3"

var (
	file_internal_service_routing_proto_routing_proto_rawDescOnce sync.Once
	file_internal_service_routing_proto_routing_proto_rawDescData []byte
)

func file_internal_service_routing_proto_routing_proto_rawDescGZIP() []byte {
	file_internal_service_routing_proto_routing_proto_rawDescOnce.Do(func() {
		file_internal_service_routing_proto_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_service_routing_proto_routing_proto_rawDesc), len(file_internal_service_routing_proto_routing_proto_rawDesc)))
	})
	return file_internal_service_routing_proto_routing_proto_rawDescData
}

var file_internal_service_routing_proto_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_service_routing_proto_routing_proto_goTypes = []any{
	(*Empty)(nil),           // 0: routing.Empty
	(*FilterBlock)(nil),     // 1: routing.FilterBlock
	(*Filters)(nil),         // 2: routing.Filters
	(*JourneyRequest)(nil),  // 3: routing.JourneyRequest
	(*StopInfo)(nil),        // 4: routing.StopInfo
	(*Leg)(nil),             // 5: routing.Leg
	(*JourneySummary)(nil),  // 6: routing.JourneySummary
	(*Journey)(nil),         // 7: routing.Journey
	(*JourneyResponse)(nil), // 8: routing.JourneyResponse
	(*HealthResponse)(nil),  // 9: routing.HealthResponse
	nil,                     // 10: routing.JourneyRequest.WeightsEntry
	nil,                     // 11: routing.JourneyResponse.WeightsUsedEntry
}
var file_internal_service_routing_proto_routing_proto_depIdxs = []int32{
	1,  // 0: routing.Filters.modes:type_name -> routing.FilterBlock
	1,  // 1: routing.Filters.main_streets:type_name -> routing.FilterBlock
	2,  // 2: routing.JourneyRequest.filters:type_name -> routing.Filters
	10, // 3: routing.JourneyRequest.weights:type_name -> routing.JourneyRequest.WeightsEntry
	4,  // 4: routing.Leg.from_stop:type_name -> routing.StopInfo
	4,  // 5: routing.Leg.to_stop:type_name -> routing.StopInfo
	6,  // 6: routing.Journey.summary:type_name -> routing.JourneySummary
	5,  // 7: routing.Journey.legs:type_name -> routing.Leg
	11, // 8: routing.JourneyResponse.weights_used:type_name -> routing.JourneyResponse.WeightsUsedEntry
	7,  // 9: routing.JourneyResponse.journeys:type_name -> routing.Journey
	3,  // 10: routing.RoutingService.FindJourneys:input_type -> routing.JourneyRequest
	0,  // 11: routing.RoutingService.HealthCheck:input_type -> routing.Empty
	8,  // 12: routing.RoutingService.FindJourneys:output_type -> routing.JourneyResponse
	9,  // 13: routing.RoutingService.HealthCheck:output_type -> routing.HealthResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_service_routing_proto_routing_proto_init() }
func file_internal_service_routing_proto_routing_proto_init() {
	if File_internal_service_routing_proto_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_routing_proto_routing_proto_rawDesc), len(file_internal_service_routing_proto_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_routing_proto_routing_proto_goTypes,
		DependencyIndexes: file_internal_service_routing_proto_routing_proto_depIdxs,
		MessageInfos:      file_internal_service_routing_proto_routing_proto_msgTypes,
	}.Build()
	File_internal_service_routing_proto_routing_proto = out.File
	file_internal_service_routing_proto_routing_proto_goTypes = nil
	file_internal_service_routing_proto_routing_proto_depIdxs = nil
}
