// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/service/geocoding/proto/geocoding.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeocodingService_Geocode_FullMethodName     = "/geocoding.GeocodingService/Geocode"
	GeocodingService_HealthCheck_FullMethodName = "/geocoding.GeocodingService/HealthCheck"
)

// GeocodingServiceClient is the client API for GeocodingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeocodingServiceClient interface {
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type geocodingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeocodingServiceClient(cc grpc.ClientConnInterface) GeocodingServiceClient {
	return &geocodingServiceClient{cc}
}

func (c *geocodingServiceClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeocodeResponse)
	err := c.cc.Invoke(ctx, GeocodingService_Geocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocodingServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GeocodingService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeocodingServiceServer is the server API for GeocodingService service.
// All implementations must embed UnimplementedGeocodingServiceServer
// for forward compatibility.
type GeocodingServiceServer interface {
	Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error)
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedGeocodingServiceServer()
}

// UnimplementedGeocodingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeocodingServiceServer struct{}

func (UnimplementedGeocodingServiceServer) Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Geocode not implemented")
}
func (UnimplementedGeocodingServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGeocodingServiceServer) mustEmbedUnimplementedGeocodingServiceServer() {}
func (UnimplementedGeocodingServiceServer) testEmbeddedByValue()                          {}

// UnsafeGeocodingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeocodingServiceServer will
// result in compilation errors.
type UnsafeGeocodingServiceServer interface {
	mustEmbedUnimplementedGeocodingServiceServer()
}

func RegisterGeocodingServiceServer(s grpc.ServiceRegistrar, srv GeocodingServiceServer) {
	// If the following call panics, it indicates UnimplementedGeocodingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeocodingService_ServiceDesc, srv)
}

func _GeocodingService_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocodingServiceServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeocodingService_Geocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocodingServiceServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeocodingService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocodingServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeocodingService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocodingServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GeocodingService_ServiceDesc is the grpc.ServiceDesc for GeocodingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeocodingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geocoding.GeocodingService",
	HandlerType: (*GeocodingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _GeocodingService_Geocode_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GeocodingService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/service/geocoding/proto/geocoding.proto",
}
