// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/service/geocoding/proto/geocoding.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_service_geocoding_proto_geocoding_proto_rawDescGZIP(), []int{0}
}

type GeocodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Bias          bool                   `protobuf:"varint,3,opt,name=bias,proto3" json:"bias,omitempty"`
	UserLat       float64                `protobuf:"fixed64,4,opt,name=user_lat,json=userLat,proto3" json:"user_lat,omitempty"` // 0 = not provided
	UserLng       float64                `protobuf:"fixed64,5,opt,name=user_lng,json=userLng,proto3" json:"user_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_geocoding_proto_geocoding_proto_rawDescGZIP(), []int{1}
}

func (x *GeocodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GeocodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GeocodeRequest) GetBias() bool {
	if x != nil {
		return x.Bias
	}
	return false
}

func (x *GeocodeRequest) GetUserLat() float64 {
	if x != nil {
		return x.UserLat
	}
	return 0
}

func (x *GeocodeRequest) GetUserLng() float64 {
	if x != nil {
		return x.UserLng
	}
	return 0
}

type GeocodeResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Latitude         float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	FormattedAddress string                 `protobuf:"bytes,3,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeocodeResult) Reset() {
	*x = GeocodeResult{}
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResult) ProtoMessage() {}

func (x *GeocodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResult.ProtoReflect.Descriptor instead.
func (*GeocodeResult) Descriptor() ([]byte, []int) {
	return file_internal_service_geocoding_proto_geocoding_proto_rawDescGZIP(), []int{2}
}

func (x *GeocodeResult) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeocodeResult) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeocodeResult) GetFormattedAddress() string {
	if x != nil {
		return x.FormattedAddress
	}
	return ""
}

type GeocodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Bias          bool                   `protobuf:"varint,4,opt,name=bias,proto3" json:"bias,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Results       []*GeocodeResult       `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeResponse) Reset() {
	*x = GeocodeResponse{}
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeResponse) ProtoMessage() {}

func (x *GeocodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeResponse.ProtoReflect.Descriptor instead.
func (*GeocodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_geocoding_proto_geocoding_proto_rawDescGZIP(), []int{3}
}

func (x *GeocodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GeocodeResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GeocodeResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GeocodeResponse) GetBias() bool {
	if x != nil {
		return x.Bias
	}
	return false
}

func (x *GeocodeResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GeocodeResponse) GetResults() []*GeocodeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GeocodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_geocoding_proto_geocoding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_geocoding_proto_geocoding_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_service_geocoding_proto_geocoding_proto protoreflect.FileDescriptor

const file_internal_service_geocoding_proto_geocoding_proto_rawDesc = "" +
	"\n" +
	"0internal/service/geocoding/proto/geocoding.proto\x12\tgeocoding\"\a\n" +
	"\x05Empty\"\x90\x01\n" +
	"\x0eGeocodeRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04bias\x18\x03 \x01(\bR\x04bias\x12\x19\n" +
	"\buser_lat\x18\x04 \x01(\x01R\auserLat\x12\x19\n" +
	"\buser_lng\x18\x05 \x01(\x01R\auserLng\"v\n" +
	"\rGeocodeResult\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12+\n" +
	"\x11formatted_address\x18\x03 \x01(\tR\x10formattedAddress\"\xd1\x01\n" +
	"\x0fGeocodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04bias\x18\x04 \x01(\bR\x04bias\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x122\n" +
	"\aresults\x18\x06 \x03(\v2\x18.geocoding.GeocodeResultR\aresults\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x90\x01\n" +
	"\x10GeocodingService\x12@\n" +
	"\aGeocode\x12\x19.geocoding.GeocodeRequest\x1a\x1a.geocoding.GeocodeResponse\x12:\n" +
	"\vHealthCheck\x12\x10.geocoding.Empty\x1a\x19.geocoding.HealthResponseBMZKgithub.com/Marwan051/final_project_backend/internal/service/geocoding/protob\x06proto3"

var (
	file_internal_service_geocoding_proto_geocoding_proto_rawDescOnce sync.Once
	file_internal_service_geocoding_proto_geocoding_proto_rawDescData []byte
)

func file_internal_service_geocoding_proto_geocoding_proto_rawDescGZIP() []byte {
	file_internal_service_geocoding_proto_geocoding_proto_rawDescOnce.Do(func() {
		file_internal_service_geocoding_proto_geocoding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_service_geocoding_proto_geocoding_proto_rawDesc), len(file_internal_service_geocoding_proto_geocoding_proto_rawDesc)))
	})
	return file_internal_service_geocoding_proto_geocoding_proto_rawDescData
}

var file_internal_service_geocoding_proto_geocoding_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_service_geocoding_proto_geocoding_proto_goTypes = []any{
	(*Empty)(nil),           // 0: geocoding.Empty
	(*GeocodeRequest)(nil),  // 1: geocoding.GeocodeRequest
	(*GeocodeResult)(nil),   // 2: geocoding.GeocodeResult
	(*GeocodeResponse)(nil), // 3: geocoding.GeocodeResponse
	(*HealthResponse)(nil),  // 4: geocoding.HealthResponse
}
var file_internal_service_geocoding_proto_geocoding_proto_depIdxs = []int32{
	2, // 0: geocoding.GeocodeResponse.results:type_name -> geocoding.GeocodeResult
	1, // 1: geocoding.GeocodingService.Geocode:input_type -> geocoding.GeocodeRequest
	0, // 2: geocoding.GeocodingService.HealthCheck:input_type -> geocoding.Empty
	3, // 3: geocoding.GeocodingService.Geocode:output_type -> geocoding.GeocodeResponse
	4, // 4: geocoding.GeocodingService.HealthCheck:output_type -> geocoding.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_service_geocoding_proto_geocoding_proto_init() }
func file_internal_service_geocoding_proto_geocoding_proto_init() {
	if File_internal_service_geocoding_proto_geocoding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_geocoding_proto_geocoding_proto_rawDesc), len(file_internal_service_geocoding_proto_geocoding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_geocoding_proto_geocoding_proto_goTypes,
		DependencyIndexes: file_internal_service_geocoding_proto_geocoding_proto_depIdxs,
		MessageInfos:      file_internal_service_geocoding_proto_geocoding_proto_msgTypes,
	}.Build()
	File_internal_service_geocoding_proto_geocoding_proto = out.File
	file_internal_service_geocoding_proto_geocoding_proto_goTypes = nil
	file_internal_service_geocoding_proto_geocoding_proto_depIdxs = nil
}
