// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/service/db_tools/proto/db_tools.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DbToolsService_NearbyTrips_FullMethodName = "/db_tools.DbToolsService/NearbyTrips"
	DbToolsService_HealthCheck_FullMethodName = "/db_tools.DbToolsService/HealthCheck"
)

// DbToolsServiceClient is the client API for DbToolsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbToolsServiceClient interface {
	NearbyTrips(ctx context.Context, in *NearbyTripsRequest, opts ...grpc.CallOption) (*NearbyTripsResponse, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type dbToolsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDbToolsServiceClient(cc grpc.ClientConnInterface) DbToolsServiceClient {
	return &dbToolsServiceClient{cc}
}

func (c *dbToolsServiceClient) NearbyTrips(ctx context.Context, in *NearbyTripsRequest, opts ...grpc.CallOption) (*NearbyTripsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NearbyTripsResponse)
	err := c.cc.Invoke(ctx, DbToolsService_NearbyTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbToolsServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DbToolsService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbToolsServiceServer is the server API for DbToolsService service.
// All implementations must embed UnimplementedDbToolsServiceServer
// for forward compatibility.
type DbToolsServiceServer interface {
	NearbyTrips(context.Context, *NearbyTripsRequest) (*NearbyTripsResponse, error)
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedDbToolsServiceServer()
}

// UnimplementedDbToolsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbToolsServiceServer struct{}

func (UnimplementedDbToolsServiceServer) NearbyTrips(context.Context, *NearbyTripsRequest) (*NearbyTripsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NearbyTrips not implemented")
}
func (UnimplementedDbToolsServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDbToolsServiceServer) mustEmbedUnimplementedDbToolsServiceServer() {}
func (UnimplementedDbToolsServiceServer) testEmbeddedByValue()                        {}

// UnsafeDbToolsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbToolsServiceServer will
// result in compilation errors.
type UnsafeDbToolsServiceServer interface {
	mustEmbedUnimplementedDbToolsServiceServer()
}

func RegisterDbToolsServiceServer(s grpc.ServiceRegistrar, srv DbToolsServiceServer) {
	// If the following call panics, it indicates UnimplementedDbToolsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DbToolsService_ServiceDesc, srv)
}

func _DbToolsService_NearbyTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearbyTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbToolsServiceServer).NearbyTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbToolsService_NearbyTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbToolsServiceServer).NearbyTrips(ctx, req.(*NearbyTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbToolsService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbToolsServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbToolsService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbToolsServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DbToolsService_ServiceDesc is the grpc.ServiceDesc for DbToolsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DbToolsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "db_tools.DbToolsService",
	HandlerType: (*DbToolsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NearbyTrips",
			Handler:    _DbToolsService_NearbyTrips_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DbToolsService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/service/db_tools/proto/db_tools.proto",
}
