// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/service/db_tools/proto/db_tools.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_service_db_tools_proto_db_tools_proto_rawDescGZIP(), []int{0}
}

type NearbyTripsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	RadiusM       float64                `protobuf:"fixed64,3,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	Starts        bool                   `protobuf:"varint,4,opt,name=starts,proto3" json:"starts,omitempty"`
	Epsg          int32                  `protobuf:"varint,5,opt,name=epsg,proto3" json:"epsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyTripsRequest) Reset() {
	*x = NearbyTripsRequest{}
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyTripsRequest) ProtoMessage() {}

func (x *NearbyTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyTripsRequest.ProtoReflect.Descriptor instead.
func (*NearbyTripsRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_db_tools_proto_db_tools_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyTripsRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NearbyTripsRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *NearbyTripsRequest) GetRadiusM() float64 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

func (x *NearbyTripsRequest) GetStarts() bool {
	if x != nil {
		return x.Starts
	}
	return false
}

func (x *NearbyTripsRequest) GetEpsg() int32 {
	if x != nil {
		return x.Epsg
	}
	return 0
}

type NearbyTripResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TripId              string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RouteId             string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	TripHeadsign        string                 `protobuf:"bytes,3,opt,name=trip_headsign,json=tripHeadsign,proto3" json:"trip_headsign,omitempty"`
	TripHeadsignAr      string                 `protobuf:"bytes,4,opt,name=trip_headsign_ar,json=tripHeadsignAr,proto3" json:"trip_headsign_ar,omitempty"`
	DirectionId         int32                  `protobuf:"varint,5,opt,name=direction_id,json=directionId,proto3" json:"direction_id,omitempty"`
	RouteShortName      string                 `protobuf:"bytes,6,opt,name=route_short_name,json=routeShortName,proto3" json:"route_short_name,omitempty"`
	RouteShortNameAr    string                 `protobuf:"bytes,7,opt,name=route_short_name_ar,json=routeShortNameAr,proto3" json:"route_short_name_ar,omitempty"`
	RouteName           string                 `protobuf:"bytes,8,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	RouteNameAr         string                 `protobuf:"bytes,9,opt,name=route_name_ar,json=routeNameAr,proto3" json:"route_name_ar,omitempty"`
	DistanceM           float64                `protobuf:"fixed64,10,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
	ClosestStopId       string                 `protobuf:"bytes,11,opt,name=closest_stop_id,json=closestStopId,proto3" json:"closest_stop_id,omitempty"`
	ClosestStopName     string                 `protobuf:"bytes,12,opt,name=closest_stop_name,json=closestStopName,proto3" json:"closest_stop_name,omitempty"`
	ClosestStopNameAr   string                 `protobuf:"bytes,13,opt,name=closest_stop_name_ar,json=closestStopNameAr,proto3" json:"closest_stop_name_ar,omitempty"`
	ClosestStopLat      float64                `protobuf:"fixed64,14,opt,name=closest_stop_lat,json=closestStopLat,proto3" json:"closest_stop_lat,omitempty"`
	ClosestStopLon      float64                `protobuf:"fixed64,15,opt,name=closest_stop_lon,json=closestStopLon,proto3" json:"closest_stop_lon,omitempty"`
	ClosestStopSequence int32                  `protobuf:"varint,16,opt,name=closest_stop_sequence,json=closestStopSequence,proto3" json:"closest_stop_sequence,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NearbyTripResult) Reset() {
	*x = NearbyTripResult{}
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyTripResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyTripResult) ProtoMessage() {}

func (x *NearbyTripResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyTripResult.ProtoReflect.Descriptor instead.
func (*NearbyTripResult) Descriptor() ([]byte, []int) {
	return file_internal_service_db_tools_proto_db_tools_proto_rawDescGZIP(), []int{2}
}

func (x *NearbyTripResult) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *NearbyTripResult) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *NearbyTripResult) GetTripHeadsign() string {
	if x != nil {
		return x.TripHeadsign
	}
	return ""
}

func (x *NearbyTripResult) GetTripHeadsignAr() string {
	if x != nil {
		return x.TripHeadsignAr
	}
	return ""
}

func (x *NearbyTripResult) GetDirectionId() int32 {
	if x != nil {
		return x.DirectionId
	}
	return 0
}

func (x *NearbyTripResult) GetRouteShortName() string {
	if x != nil {
		return x.RouteShortName
	}
	return ""
}

func (x *NearbyTripResult) GetRouteShortNameAr() string {
	if x != nil {
		return x.RouteShortNameAr
	}
	return ""
}

func (x *NearbyTripResult) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *NearbyTripResult) GetRouteNameAr() string {
	if x != nil {
		return x.RouteNameAr
	}
	return ""
}

func (x *NearbyTripResult) GetDistanceM() float64 {
	if x != nil {
		return x.DistanceM
	}
	return 0
}

func (x *NearbyTripResult) GetClosestStopId() string {
	if x != nil {
		return x.ClosestStopId
	}
	return ""
}

func (x *NearbyTripResult) GetClosestStopName() string {
	if x != nil {
		return x.ClosestStopName
	}
	return ""
}

func (x *NearbyTripResult) GetClosestStopNameAr() string {
	if x != nil {
		return x.ClosestStopNameAr
	}
	return ""
}

func (x *NearbyTripResult) GetClosestStopLat() float64 {
	if x != nil {
		return x.ClosestStopLat
	}
	return 0
}

func (x *NearbyTripResult) GetClosestStopLon() float64 {
	if x != nil {
		return x.ClosestStopLon
	}
	return 0
}

func (x *NearbyTripResult) GetClosestStopSequence() int32 {
	if x != nil {
		return x.ClosestStopSequence
	}
	return 0
}

type NearbyTripsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	RadiusM       float64                `protobuf:"fixed64,3,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	Starts        bool                   `protobuf:"varint,4,opt,name=starts,proto3" json:"starts,omitempty"`
	Epsg          int32                  `protobuf:"varint,5,opt,name=epsg,proto3" json:"epsg,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Trips         []*NearbyTripResult    `protobuf:"bytes,7,rep,name=trips,proto3" json:"trips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyTripsResponse) Reset() {
	*x = NearbyTripsResponse{}
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyTripsResponse) ProtoMessage() {}

func (x *NearbyTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyTripsResponse.ProtoReflect.Descriptor instead.
func (*NearbyTripsResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_db_tools_proto_db_tools_proto_rawDescGZIP(), []int{3}
}

func (x *NearbyTripsResponse) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NearbyTripsResponse) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *NearbyTripsResponse) GetRadiusM() float64 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

func (x *NearbyTripsResponse) GetStarts() bool {
	if x != nil {
		return x.Starts
	}
	return false
}

func (x *NearbyTripsResponse) GetEpsg() int32 {
	if x != nil {
		return x.Epsg
	}
	return 0
}

func (x *NearbyTripsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NearbyTripsResponse) GetTrips() []*NearbyTripResult {
	if x != nil {
		return x.Trips
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DbConnected   bool                   `protobuf:"varint,2,opt,name=db_connected,json=dbConnected,proto3" json:"db_connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_db_tools_proto_db_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_db_tools_proto_db_tools_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetDbConnected() bool {
	if x != nil {
		return x.DbConnected
	}
	return false
}

var File_internal_service_db_tools_proto_db_tools_proto protoreflect.FileDescriptor

const file_internal_service_db_tools_proto_db_tools_proto_rawDesc = "" +
	"\n" +
	".internal/service/db_tools/proto/db_tools.proto\x12\bdb_tools\"\a\n" +
	"\x05Empty\"\x7f\n" +
	"\x12NearbyTripsRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x19\n" +
	"\bradius_m\x18\x03 \x01(\x01R\aradiusM\x12\x16\n" +
	"\x06starts\x18\x04 \x01(\bR\x06starts\x12\x12\n" +
	"\x04epsg\x18\x05 \x01(\x05R\x04epsg\"\x80\x05\n" +
	"\x10NearbyTripResult\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12#\n" +
	"\rtrip_headsign\x18\x03 \x01(\tR\ftripHeadsign\x12(\n" +
	"\x10trip_headsign_ar\x18\x04 \x01(\tR\x0etripHeadsignAr\x12!\n" +
	"\fdirection_id\x18\x05 \x01(\x05R\vdirectionId\x12(\n" +
	"\x10route_short_name\x18\x06 \x01(\tR\x0erouteShortName\x12-\n" +
	"\x13route_short_name_ar\x18\a \x01(\tR\x10routeShortNameAr\x12\x1d\n" +
	"\n" +
	"route_name\x18\b \x01(\tR\trouteName\x12\"\n" +
	"\rroute_name_ar\x18\t \x01(\tR\vrouteNameAr\x12\x1d\n" +
	"\n" +
	"distance_m\x18\n" +
	" \x01(\x01R\tdistanceM\x12&\n" +
	"\x0fclosest_stop_id\x18\v \x01(\tR\rclosestStopId\x12*\n" +
	"\x11closest_stop_name\x18\f \x01(\tR\x0fclosestStopName\x12/\n" +
	"\x14closest_stop_name_ar\x18\r \x01(\tR\x11closestStopNameAr\x12(\n" +
	"\x10closest_stop_lat\x18\x0e \x01(\x01R\x0eclosestStopLat\x12(\n" +
	"\x10closest_stop_lon\x18\x0f \x01(\x01R\x0eclosestStopLon\x122\n" +
	"\x15closest_stop_sequence\x18\x10 \x01(\x05R\x13closestStopSequence\"\xc8\x01\n" +
	"\x13NearbyTripsResponse\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x19\n" +
	"\bradius_m\x18\x03 \x01(\x01R\aradiusM\x12\x16\n" +
	"\x06starts\x18\x04 \x01(\bR\x06starts\x12\x12\n" +
	"\x04epsg\x18\x05 \x01(\x05R\x04epsg\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x120\n" +
	"\x05trips\x18\a \x03(\v2\x1a.db_tools.NearbyTripResultR\x05trips\"K\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fdb_connected\x18\x02 \x01(\bR\vdbConnected2\x96\x01\n" +
	"\x0eDbToolsService\x12J\n" +
	"\vNearbyTrips\x12\x1c.db_tools.NearbyTripsRequest\x1a\x1d.db_tools.NearbyTripsResponse\x128\n" +
	"\vHealthCheck\x12\x0f.db_tools.Empty\x1a\x18.db_tools.HealthResponseBLZJgithub.com/Marwan051/final_project_backend/internal/service/db_tools/protob\x06proto3"

var (
	file_internal_service_db_tools_proto_db_tools_proto_rawDescOnce sync.Once
	file_internal_service_db_tools_proto_db_tools_proto_rawDescData []byte
)

func file_internal_service_db_tools_proto_db_tools_proto_rawDescGZIP() []byte {
	file_internal_service_db_tools_proto_db_tools_proto_rawDescOnce.Do(func() {
		file_internal_service_db_tools_proto_db_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_service_db_tools_proto_db_tools_proto_rawDesc), len(file_internal_service_db_tools_proto_db_tools_proto_rawDesc)))
	})
	return file_internal_service_db_tools_proto_db_tools_proto_rawDescData
}

var file_internal_service_db_tools_proto_db_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_service_db_tools_proto_db_tools_proto_goTypes = []any{
	(*Empty)(nil),               // 0: db_tools.Empty
	(*NearbyTripsRequest)(nil),  // 1: db_tools.NearbyTripsRequest
	(*NearbyTripResult)(nil),    // 2: db_tools.NearbyTripResult
	(*NearbyTripsResponse)(nil), // 3: db_tools.NearbyTripsResponse
	(*HealthResponse)(nil),      // 4: db_tools.HealthResponse
}
var file_internal_service_db_tools_proto_db_tools_proto_depIdxs = []int32{
	2, // 0: db_tools.NearbyTripsResponse.trips:type_name -> db_tools.NearbyTripResult
	1, // 1: db_tools.DbToolsService.NearbyTrips:input_type -> db_tools.NearbyTripsRequest
	0, // 2: db_tools.DbToolsService.HealthCheck:input_type -> db_tools.Empty
	3, // 3: db_tools.DbToolsService.NearbyTrips:output_type -> db_tools.NearbyTripsResponse
	4, // 4: db_tools.DbToolsService.HealthCheck:output_type -> db_tools.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_service_db_tools_proto_db_tools_proto_init() }
func file_internal_service_db_tools_proto_db_tools_proto_init() {
	if File_internal_service_db_tools_proto_db_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_db_tools_proto_db_tools_proto_rawDesc), len(file_internal_service_db_tools_proto_db_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_db_tools_proto_db_tools_proto_goTypes,
		DependencyIndexes: file_internal_service_db_tools_proto_db_tools_proto_depIdxs,
		MessageInfos:      file_internal_service_db_tools_proto_db_tools_proto_msgTypes,
	}.Build()
	File_internal_service_db_tools_proto_db_tools_proto = out.File
	file_internal_service_db_tools_proto_db_tools_proto_goTypes = nil
	file_internal_service_db_tools_proto_db_tools_proto_depIdxs = nil
}
